"""Azerbaijan KB v2: question-driven everyday-knowledge cards (English, with Azerbaijani terms).

Each card: (category, source_key, written_for_question_ids, text_en, keywords).
Written from the BLEnD *question types* plus the cited sources; gold answers were not consulted.
"""

SOURCES = {
    "cuisine": ("Azerbaijani cuisine", "Wikipedia", "https://en.wikipedia.org/wiki/Azerbaijani_cuisine", "high"),
    "edu": ("Education in Azerbaijan", "Wikipedia", "https://en.wikipedia.org/wiki/Education_in_Azerbaijan", "high"),
    "hol": ("Public holidays in Azerbaijan", "Wikipedia", "https://en.wikipedia.org/wiki/Public_holidays_in_Azerbaijan", "high"),
    "sport": ("Sport in Azerbaijan", "Wikipedia", "https://en.wikipedia.org/wiki/Sport_in_Azerbaijan", "high"),
    "labour": ("Every leave policy in Azerbaijan explained", "Skuad (summary of the Labour Code)",
               "https://www.skuad.io/leave-policy/azerbaijan", "medium"),
    "labour2": ("Guide to hiring in Azerbaijan", "Airswift (summary of the Labour Code)",
                "https://www.airswift.com/hiring-guide/azerbaijan", "medium"),
    "teachers": ("Azerbaijan celebrates Teachers' Day", "Report.az",
                 "https://report.az/en/education-and-science/azerbaijan-celebrates-teachers-day", "high"),
    "marriage": ("Average marriage age rises in Azerbaijan", "AzerNews", "https://www.azernews.az/nation/159444.html", "medium"),
    "culture": ("Culture of Azerbaijan", "Wikipedia", "https://en.wikipedia.org/wiki/Culture_of_Azerbaijan", "high"),
    "economy": ("Economy of Azerbaijan", "Wikipedia", "https://en.wikipedia.org/wiki/Economy_of_Azerbaijan", "high"),
    "general": ("Azerbaijan (compiled general reference)", "Wikipedia and general reference",
                "https://en.wikipedia.org/wiki/Azerbaijan", "medium"),
}

CARDS = [
    # ---------------- food ----------------
    ("food", "cuisine", ["Ne-ar-31", "New-am-02", "New-ha-07", "New-in-03", "Ne-ar-36"],
     "Plov (pilaf, aş) is Azerbaijan's most famous dish and the centrepiece of festive meals, with over 200 varieties such as shah plov; dolma (vine- or cabbage-leaf rolls, UNESCO-listed), kebab (kabab: lülə and tikə), qutab, düşbərə, piti and dovğa are also iconic national dishes.",
     ["plov", "pilaf", "dolma", "kebab", "qutab", "national dish"]),
    ("food", "cuisine", ["Ne-ar-34", "Na-ko-09", "Ki-pe-43", "New-as-02"],
     "Bread (çörək) is indispensable at every Azerbaijani meal and treated as sacred; the popular breads are tandır çörəyi (tandoor bread), lavaş (UNESCO-listed thin flatbread) and yuxa. Meals start with fresh herbs (göyərti), white cheese, pickles (turşu) and salad.",
     ["bread", "çörək", "tandir bread", "lavash", "fresh herbs", "pickles"]),
    ("food", "general", ["Ne-ar-32", "New-gr-05", "Ki-pe-34", "New-gr-13"],
     "A typical Azerbaijani breakfast is bread with white cheese (pendir), butter, honey, jam, eggs (omelette or tomato-egg \"pomidor-yumurta\"), sausage, olives and fresh vegetables, always with black tea (çay).",
     ["breakfast", "cheese", "butter", "honey", "eggs", "tea"]),
    ("food", "cuisine", ["Ca-sp-14", "Kik-in-16", "Na-ko-02", "New-as-05", "New-as-58", "Ne-ar-43"],
     "Black tea (çay) is the most popular drink in Azerbaijan: it is served in pear-shaped armudu glasses with sugar cubes, lemon and fruit preserves (mürəbbə), and offered to every guest and at work. Tea is drunk in traditional tea houses (çayxana).",
     ["tea", "çay", "black tea", "armudu", "jam", "lemon"]),
    ("food", "general", ["Ne-ar-44"],
     "Coffee in Azerbaijan (often Turkish coffee) is usually served with sweets, chocolate or pakhlava, and a glass of water.",
     ["coffee", "Turkish coffee", "sweets", "chocolate"]),
    ("food", "general", ["Al-en-01", "Sa-en-7", "New-su-01", "Al-en-08", "Al-en-09", "New-en-01", "New-ch-04"],
     "Popular snacks in Azerbaijan are roasted sunflower seeds (tum), nuts, chips, popcorn, qutab, pirozhki (fried pies), corn, biscuits and fruit; children's snacks are fruit, biscuits, cookies and juice.",
     ["sunflower seeds", "tum", "chips", "popcorn", "qutab", "pirozhki"]),
    ("food", "general", ["Al-en-02", "New-ch-07"],
     "In Azerbaijan beer is usually accompanied by boiled crayfish, dried fish, chips, nuts and kebab; vodka and other hard liquor are served with kebab, pickles (turşu), salads and fresh herbs.",
     ["crayfish", "dried fish", "kebab", "pickles", "beer", "vodka"]),
    ("food", "cuisine", ["Al-en-04", "Ne-ar-37", "Na-ko-08", "New-ch-54"],
     "The pomegranate (nar) is Azerbaijan's symbolic fruit, celebrated at the Goychay Pomegranate Festival and offered to visitors; apples (especially from Quba), persimmons (xurma), quince, grapes and figs are other favourites, with pomegranate, persimmon, apple and quince typical in autumn.",
     ["pomegranate", "nar", "apple", "persimmon", "quince", "Goychay"]),
    ("food", "general", ["New-az-11"],
     "In summer Azerbaijanis most often eat watermelon (qarpız), melon (yemiş), cherries, apricots, peaches and strawberries.",
     ["watermelon", "melon", "cherries", "apricots", "summer"]),
    ("food", "general", ["Al-en-06", "Jod-ch-48", "Ne-ar-39", "New-en-05", "Jod-ch-13", "New-gr-06", "Sa-en-6"],
     "Döner (doner kebab) is the most popular street and fast food in Azerbaijan, as well as the cheapest quick meal and a favourite of students and young people; lavash wraps, shaurma, qutab, burgers and pizza are also common. Workday lunches are often soup and a main dish in canteens, or döner.",
     ["döner", "doner kebab", "shaurma", "qutab", "fast food"]),
    ("food", "general", ["Ca-sp-05", "Ca-sp-06", "Th-en-35", "Ca-sp-11"],
     "Azerbaijanis usually eat three meals a day; dinner is the main meal, shared by the whole family, and weekends (especially Sunday) are the usual time for a big family meal.",
     ["three meals", "dinner", "family", "Sunday"]),
    ("food", "cuisine", ["Ca-sp-09", "New-gr-15", "New-spme-05", "New-pe-02"],
     "Traditional Azerbaijani sweets are pakhlava (paxlava), shekerbura (şəkərbura), shorgoghal (şorqoğal), badambura and halva (Sheki halva is famous); after meals people have tea with jam (mürəbbə), fruit and sweets. Pakhlava, Sheki halva, tea and jam are popular edible souvenirs.",
     ["pakhlava", "shekerbura", "shorgoghal", "halva", "Sheki halva", "jam"]),
    ("food", "general", ["Jod-ch-01", "New-ha-09"],
     "Azerbaijanis eat with a fork, spoon and knife; plov is cooked in a large pot (qazan), and lavash and qutab are baked on a convex griddle (saj).",
     ["fork", "spoon", "qazan", "saj"]),
    ("food", "general", ["Jod-ch-04", "New-spme-68", "New-as-15", "New-su-15"],
     "Popular soft drinks in Azerbaijan are Coca-Cola, Fanta and local mineral waters (Sirab, Badamlı); traditional non-alcoholic drinks are şərbət (sherbet), ayran (salty yogurt drink) and kompot, which are favourites in hot weather; children drink juice, kompot and milk.",
     ["Coca-Cola", "Sirab", "Badamli", "sherbet", "ayran", "kompot"]),
    ("food", "general", ["Jod-ch-06", "New-az-69", "New-az-70", "New-gr-08", "New-gr-89", "Ca-sp-19"],
     "Vodka (araq) is the most popular traditional alcoholic drink of Azerbaijani men, along with beer and cognac; women more often drink wine or champagne. At weddings vodka, wine and soft drinks are served; young people in clubs drink cocktails, beer and whisky.",
     ["vodka", "araq", "beer", "cognac", "wine", "champagne"]),
    ("food", "economy", ["New-az-05", "New-ch-13"],
     "Azerbaijan's main wine regions are Shamakhi, Ganja-Goygol and Tovuz; Xırdalan is the best-known beer brand, and Göygöl wine and Azerbaijani cognac are well known.",
     ["Shamakhi", "Ganja", "Goygol", "Tovuz", "Xirdalan"]),
    ("food", "general", ["Jod-ch-09", "Ne-ar-33", "New-ch-02", "Jod-ch-07"],
     "Typical Azerbaijani mealtimes are breakfast around 8:00, lunch around 13:00 and dinner around 19:00-20:00; a restaurant dinner with friends often lasts 2-3 hours.",
     ["breakfast", "lunch", "dinner", "13:00", "19:00"]),
    ("food", "cuisine", ["Jod-ch-12", "New-ch-09", "New-as-14", "Na-ko-04"],
     "Popular Azerbaijani soups are dovğa (yogurt-herb soup), piti (mutton and chickpea soup in clay pots), düşbərə (dumpling soup), kufta-bozbash and khash (xaş, cow-foot soup eaten on winter mornings, also a hangover cure). In cold weather people eat khash, piti and bozbash and drink tea.",
     ["dovga", "piti", "dushbara", "bozbash", "khash", "soup"]),
    ("food", "cuisine", ["Jod-ch-15", "New-as-07", "New-az-12"],
     "Fish eaten in Azerbaijan comes from the Caspian Sea: sturgeon (nərə, grilled as kebab), kutum, Caspian salmon and black caviar. The famous fish dish is lavangi (kutum stuffed with walnuts and onion) from Lankaran; Lankaran and the Caspian coast (Baku, Neftchala) are known for seafood.",
     ["sturgeon", "kutum", "caviar", "lavangi", "Lankaran", "Caspian"]),
    ("food", "cuisine", ["Ki-pe-32", "New-su-83", "Ji-ko-09"],
     "When hosting guests or at weddings Azerbaijanis serve plov, dolma, kebab, salads, herbs, cheese and fruit, followed by tea with sweets.",
     ["plov", "dolma", "kebab", "tea", "guests"]),
    ("food", "general", ["Ki-pe-36"],
     "Apart from Azerbaijani food, Turkish cuisine (döner, lahmacun, pide) is the most popular in Azerbaijan, followed by Russian, Georgian (khachapuri, khinkali), Italian and Japanese (sushi).",
     ["Turkish food", "döner", "Georgian food", "sushi"]),
    ("food", "cuisine", ["Ki-pe-40", "Sa-en-13", "New-ha-08"],
     "Khash (xaş, cow-foot soup with garlic) and kəllə-paça (sheep head and trotters) are the Azerbaijani foods foreigners most often find disgusting; they are divisive and loved by older people.",
     ["khash", "xash", "kelle-pacha", "divisive"]),
    ("food", "general", ["Kik-in-24"],
     "In Azerbaijani fast-food restaurants chicken is usually served with French fries or rice.",
     ["French fries", "rice", "chicken"]),
    ("food", "general", ["Na-ko-05", "Sa-en-1", "New-en-12"],
     "The most popular delivery foods in Baku are döner, pizza, burgers and sushi, ordered via Wolt and Bolt Food; popular fast-food chains are McDonald's, KFC, Burger King and Papa John's.",
     ["delivery", "pizza", "sushi", "Wolt", "McDonald's", "KFC"]),
    ("food", "cuisine", ["Na-ko-07", "New-ch-01"],
     "Lamb/mutton is the most consumed meat in Azerbaijan, followed by beef and chicken; pork is rarely eaten. Barbecue (kabab/shashlik) is made mostly from lamb (tikə, lülə), as well as chicken and sturgeon.",
     ["lamb", "mutton", "beef", "chicken", "shashlik", "kebab"]),
    ("food", "general", ["Na-ko-11", "Na-ko-24"],
     "While watching football Azerbaijanis eat sunflower seeds, nuts and chips and drink tea or beer, often in tea houses.",
     ["sunflower seeds", "nuts", "tea", "beer"]),
    ("food", "general", ["Na-ko-15", "New-ch-14", "New-su-10", "New-am-15"],
     "Nourishing food in Azerbaijan: sick people are given chicken soup (toyuq şorbası), tea with lemon and honey, and raspberry jam; new mothers are given chicken soup, halva-like quymaq (flour, butter and sugar) and nutritious food; pregnant women are encouraged to eat fruit (especially pomegranate), milk and greens.",
     ["chicken soup", "honey", "lemon", "quymaq", "pomegranate"]),
    ("food", "cuisine", ["Ne-ar-38", "Ne-ar-10"],
     "Food given as charity (ehsan, nəzir) in Azerbaijan is usually plov, halva and sacrificial meat; at Qurban Bayramı (Eid al-Adha) a sheep is sacrificed and the meat shared with the poor, relatives and neighbours.",
     ["charity", "ehsan", "plov", "halva", "sacrifice", "Qurban"]),
    ("food", "cuisine", ["New-ch-08", "New-pe-11", "New-am-04", "New-ch-05"],
     "Key Azerbaijani seasonings are saffron (used in over 50 dishes, especially plov), sumac (with kebab), dill, coriander, mint, black pepper, onion and garlic; narsharab (pomegranate sauce) is the classic sauce for kebab. Azerbaijani food is generally not spicy.",
     ["saffron", "sumac", "dill", "mint", "narsharab", "not spicy"]),
    ("food", "economy", ["New-as-01", "New-spme-04", "Ji-ko-14"],
     "Oil and gas make up about 90% of Azerbaijan's exports. Main agricultural products are wheat and other grains, cotton, hazelnuts, fruit and vegetables (tomatoes, apples, persimmons), grapes and tea; hazelnuts and fresh fruit and vegetables are the top agricultural exports.",
     ["oil", "gas", "hazelnuts", "cotton", "tomatoes", "export"]),
    ("food", "cuisine", ["New-en-10"],
     "The most eaten cheese in Azerbaijan is white brined cheese (ağ pendir); motal (cheese aged in sheepskin) and suluguni are also popular.",
     ["white cheese", "pendir", "motal", "suluguni"]),
    ("food", "general", ["New-ha-13", "New-en-11"],
     "The most common vegetables in Azerbaijan are tomatoes, cucumbers, potatoes, onions, eggplant and peppers, along with fresh herbs (göyərti) such as dill, coriander and green onion.",
     ["tomato", "cucumber", "potato", "eggplant", "herbs"]),
    ("food", "general", ["New-su-09"],
     "Azerbaijanis usually cook with sunflower oil and butter (including clarified butter for plov).",
     ["sunflower oil", "butter"]),
    ("food", "general", ["Kik-in-17", "Ne-ar-06", "Ne-ar-09"],
     "During Ramadan Azerbaijani Muslims break the fast (iftar) with dates and water, then soup, plov and sweets; at Ramazan Bayramı families visit relatives and serve pakhlava, shekerbura and plov.",
     ["Ramadan", "dates", "plov", "pakhlava", "Ramazan Bayrami"]),
    ("food", "general", ["Ki-pe-39", "Sa-en-9"],
     "For picnics Azerbaijanis grill kebab (shashlik) over a mangal and bring bread, vegetables, herbs, fruit and tea; at the beach people eat corn, watermelon, sunflower seeds and ice cream.",
     ["picnic", "shashlik", "kebab", "mangal", "watermelon", "corn"]),
    ("food", "general", ["New-in-01"],
     "Popular coffee-shop chains in Baku include Coffee Moffie, Starbucks and Gloria Jean's, while traditional tea houses (çayxana) remain everywhere.",
     ["Coffee Moffie", "Starbucks", "tea house"]),

    # ---------------- family ----------------
    ("family", "general", ["Ca-sp-38"],
     "In Baku most families live in apartments in multi-storey buildings; in the regions families usually live in private houses with a courtyard (həyət evi).",
     ["apartment", "flat", "private house", "courtyard"]),
    ("family", "general", ["Ca-sp-41", "New-az-60", "New-pe-59"],
     "In Azerbaijan elderly parents traditionally live with their children, usually with a son's family; care homes are rare. Grandmothers (nənə) and grandparents look after children when both parents work, and three generations often live together.",
     ["elderly", "son", "grandmother", "grandparents", "three generations"]),
    ("family", "labour", ["Ca-sp-42", "Ca-sp-43"],
     "Azerbaijani mothers get 126 days (18 weeks) of paid maternity leave (70 days before and 56 days after birth); fathers get 14 days (2 weeks) of unpaid paternity leave.",
     ["maternity leave", "126 days", "18 weeks", "paternity leave", "14 days"]),
    ("family", "general", ["Gu-ch-16", "Gu-ch-18", "Ta-pe-13"],
     "The average Azerbaijani household has about 4-5 people; couples today usually have 2-3 children, while in the parents' generation families often had 4-6 children.",
     ["household size", "two children", "three children"]),
    ("family", "general", ["Ji-ko-16", "Ji-ko-28"],
     "After childbirth an Azerbaijani mother and baby traditionally stay at home for 40 days (çillə), often helped by the mother's mother; the baby's 40th day (qırxı) and the cradle celebration (beşik toyu) are the first celebrations after birth.",
     ["40 days", "chilla", "cradle", "beshik toyu"]),
    ("family", "general", ["Ji-ko-29", "Al-en-39", "New-su-71", "New-spme-78"],
     "Birthdays in Azerbaijan are celebrated with a cake and the song \"Happy Birthday\" (\"Ad günün mübarək\"); children get toys, clothes, money or phones as presents. The first birthday and milestone ages are celebrated most grandly.",
     ["birthday", "cake", "Happy Birthday", "Ad gunun mubarek"]),
    ("family", "hol", ["Ji-ko-25", "New-as-64", "Th-en-38"],
     "Novruz Bayramı (spring New Year, 20-24 March) is the most important family holiday in Azerbaijan, when all family members reunite; New Year (31 December), Ramazan Bayramı and Qurban Bayramı are also family holidays.",
     ["Novruz", "family holiday", "New Year", "Ramazan Bayrami", "Qurban Bayrami"]),
    ("family", "general", ["Ji-ko-27", "Ji-ko-22", "New-pe-53", "New-pe-54"],
     "When visiting elderly parents Azerbaijanis usually bring sweets (a box of pakhlava, cake or chocolates), fruit and tea; a first salary is typically spent on gifts for parents. Women receive flowers, perfume and jewellery on 8 March (Women's Day), which serves as Mother's Day.",
     ["sweets", "cake", "fruit", "flowers", "perfume", "March 8"]),
    ("family", "general", ["Ji-ko-24", "Al-en-40", "Th-en-36", "Al-en-43"],
     "Popular family places in Baku are the Seaside Boulevard (Dənizkənarı Milli Park), parks and playgrounds, and children's entertainment centres in shopping malls (e.g. Ganjlik Mall, Park Bulvar). On weekends families visit relatives, walk on the Boulevard, go to malls or have picnics.",
     ["Boulevard", "park", "playground", "mall", "visit relatives"]),
    ("family", "general", ["New-ko-01", "New-am-72", "New-am-73"],
     "Popular cartoons among Azerbaijani children are \"Masha and the Bear\" and Turkish cartoons such as \"Rafadan Tayfa\" and \"Pepee\"; classic Azerbaijani animations are based on folk tales like \"Cırtdan\".",
     ["Masha and the Bear", "Rafadan Tayfa", "Pepee", "Cirtdan"]),
    ("family", "culture", ["New-ko-06", "New-ko-03"],
     "The most popular Azerbaijani folk tales for children are \"Cırtdan\" (Tom Thumb), \"Tıq-tıq xanım\", \"Məlik Məmməd\" and Molla Nasreddin anecdotes; \"Cücələrim\" (My Little Chicks) is the best-known children's song.",
     ["Cirtdan", "Tiq-tiq xanim", "Molla Nasreddin", "Cucelerim"]),
    ("family", "general", ["New-ch-49"],
     "Azerbaijani families communicate remotely mostly through WhatsApp (messages and video calls), phone calls and Instagram.",
     ["WhatsApp", "phone call", "video call", "Instagram"]),
    ("family", "general", ["Ca-sp-45", "New-ch-51", "Na-ko-37"],
     "The most popular domestic vacation spots in Azerbaijan are Gabala, Sheki, Guba-Qusar (Shahdag) and the Caspian beaches of Nabran; families usually book hotels or resorts, or go to summer houses (bağ evi/dacha) on the Absheron peninsula.",
     ["Gabala", "Sheki", "Guba", "Shahdag", "Nabran", "resort"]),
    ("family", "general", ["Na-ko-45", "New-pe-85"],
     "Turkey (Antalya, Istanbul) is the most popular foreign holiday and honeymoon destination for Azerbaijanis, followed by Georgia, Dubai (UAE) and the Maldives.",
     ["Turkey", "Antalya", "Istanbul", "Georgia", "Dubai", "Maldives"]),
    ("family", "general", ["New-en-47"],
     "Azerbaijani house yards and Absheron summer houses typically have fruit trees (figs, pomegranates, mulberries), grapevines (tənək), vegetables and a place for barbecue.",
     ["fig", "grapevine", "fruit trees", "mulberry"]),
    ("family", "general", ["New-en-50", "New-en-49"],
     "Mammadov (Məmmədov) is the most common surname in Azerbaijan, followed by Aliyev, Hasanov, Huseynov and Guliyev; the best-known family is the Aliyev family.",
     ["Mammadov", "Aliyev", "Hasanov", "Huseynov", "surname"]),
    ("family", "culture", ["New-en-55", "New-pe-49", "New-spme-60"],
     "Most Azerbaijanis are Muslim (mainly Shia, with a Sunni minority) in a secular state; religious families pray at the mosque, especially on Friday, or at home, and visit shrines (pir) such as Bibi-Heybat Mosque.",
     ["Islam", "Shia", "mosque", "Friday", "Bibi-Heybat"]),
    ("family", "edu", ["New-en-56", "Ki-pe-24"],
     "Russian is the most widely spoken foreign language in Azerbaijani families, followed by English and Turkish; besides English, Russian is the main other language taught in schools.",
     ["Russian", "English", "Turkish", "language"]),
    ("family", "general", ["New-en-59", "New-az-39", "New-spme-37"],
     "Russia is the most common emigration destination for Azerbaijanis, followed by Turkey, Germany and the USA. Turkey is the most popular study-abroad destination, along with Russia, the UK and Germany.",
     ["Russia", "Turkey", "Germany", "emigration", "study abroad"]),
    ("family", "general", ["New-ko-04", "New-ko-05"],
     "Popular toys in Azerbaijan: boys like toy cars, balls and toy guns; girls like dolls (e.g. Barbie) and kitchen sets.",
     ["toy cars", "ball", "doll", "Barbie"]),
    ("family", "hol", ["New-spme-65", "Kik-in-02", "New-spme-76"],
     "Azerbaijan celebrates Independence Day on 28 May and Victory Day on 8 November with flags, concerts, fireworks and events on State Flag Square and the Seaside Boulevard in Baku.",
     ["Independence Day", "May 28", "Victory Day", "flags", "concerts", "State Flag Square"]),
    ("family", "general", ["New-su-75", "Th-en-43"],
     "A typical Azerbaijani family owns one car; popular brands are Toyota (the Prius is the classic taxi), Hyundai, Kia, Mercedes and older Lada (Zhiguli).",
     ["one car", "Toyota", "Prius", "Hyundai", "Lada"]),
    ("family", "general", ["Sa-en-31"],
     "Cats are the most common pets in Azerbaijan, followed by dogs and birds.",
     ["cat", "dog", "pet"]),
    ("family", "culture", ["Sa-en-37", "Th-en-39", "New-pe-83", "New-as-76"],
     "Nard (backgammon) is the most popular board game in Azerbaijan, along with chess, dominoes and lotto; durak is the most common card game. During Novruz families crack painted eggs (egg tapping) and children jump over bonfires.",
     ["nard", "backgammon", "chess", "domino", "lotto", "durak"]),
    ("family", "marriage", ["Ta-pe-10", "Ta-pe-11", "Th-en-41"],
     "According to official statistics Azerbaijani men marry at about 28-30 and women at about 24-25 on average (2022: women 24.1, men 28.5); couples usually have their first child about a year after marriage (around 25-26).",
     ["marriage age", "28", "24", "first child"]),
    ("family", "general", ["Th-en-37", "Ji-ko-26"],
     "Azerbaijani children usually live with their parents until marriage; becoming independent is tied to marriage and a stable job, typically in the mid-to-late twenties.",
     ["marriage", "independence", "job"]),
    ("family", "general", ["Th-en-45", "Th-en-44", "Sa-en-32"],
     "On weekday evenings Azerbaijani families have dinner and tea together and watch TV series (often Turkish dramas); weekend family meals are typically plov, dolma or kebab.",
     ["dinner", "tea", "TV series", "Turkish dramas", "plov"]),
    ("family", "general", ["Nu-in-20", "New-pe-47"],
     "Children's Day in Azerbaijan is celebrated on 1 June; students celebrate on 17 November (International Students' Day).",
     ["Children's Day", "June 1", "November 17"]),
    ("family", "general", ["New-ha-66", "New-az-73"],
     "Azerbaijani weddings are usually held in large wedding palaces (şadlıq sarayı) or restaurants and are big, often with 300-500 or more guests.",
     ["wedding palace", "shadliq sarayi", "restaurant", "300", "500"]),

    # ---------------- education ----------------
    ("education", "edu", ["Al-en-16", "Jo-sp-39", "Gu-ch-31", "Ni-en-15"],
     "Children in Azerbaijan attend kindergarten (uşaq bağçası) from about age 3 and a school-preparation year at 5; school starts at age 6. Primary school covers grades 1-4 (4 years), general secondary grades 5-9 (starting at about age 10) and full secondary grades 10-11.",
     ["kindergarten", "age 3", "age 6", "grades 1-4", "4 years"]),
    ("education", "edu", ["Gu-ch-32", "Ni-en-06", "Ki-pe-17", "New-spme-27"],
     "Education in Azerbaijan is compulsory through grade 9 (9 years, from age 6); full school education is 11 years, and most people complete secondary school, with a large share going on to university.",
     ["compulsory", "9 years", "11 years", "grade 9"]),
    ("education", "edu", ["New-am-41", "Th-en-49", "Ji-ko-42"],
     "The State Examination Centre (DİM) runs the national graduation exams at grade 9 (the first national-level exam) and grade 11, and the university entrance exam (maximum 700 points), the most important exam for high school students; it covers Azerbaijani language, mathematics and a foreign language, plus subjects of the chosen group.",
     ["DIM", "State Examination Centre", "entrance exam", "700", "grade 9", "grade 11"]),
    ("education", "edu", ["Gu-ch-38", "Ni-en-11", "Ni-en-03", "Ni-en-13"],
     "In Azerbaijan a bachelor's degree takes 4 years (medicine 6) and a master's degree 2 years. Students enter university at about 17-18 and graduate around 21-22.",
     ["4 years", "bachelor", "master", "2 years", "17"]),
    ("education", "teachers", ["Nu-in-06", "New-su-45"],
     "Azerbaijan celebrates Teachers' Day on 5 October (since 1994, together with World Teachers' Day); Knowledge Day on 15 September marks the start of the school year.",
     ["Teachers' Day", "October 5", "Knowledge Day", "September 15"]),
    ("education", "general", ["Nu-in-05", "Nu-in-04", "An-ar-03", "Jo-sp-36", "New-en-70"],
     "The Azerbaijani school year begins on 15 September (Knowledge Day) and ends in late May/June; it has two semesters, with final exams in May-June. Schools have winter, spring (Novruz) and long summer holidays of about three months (12-13 weeks).",
     ["September 15", "two semesters", "May", "June", "summer holidays"]),
    ("education", "general", ["Ki-pe-30", "Ni-en-09"],
     "Most Azerbaijani schools are closed on Saturday and Sunday (a five-day week), though some schools still teach older grades six days a week.",
     ["Saturday", "Sunday", "five days", "six days"]),
    ("education", "general", ["Nu-in-11", "Gu-ch-40", "Jo-sp-31", "Ni-en-02", "An-ar-08", "New-ch-75"],
     "Many Azerbaijani schools work in two shifts: the first shift starts at 8:00 and ends around 13:00, the second shift runs from about 13:30 to 18:00. Lessons last 45 minutes; younger pupils finish around 12:00-13:00 and students spend about 5-6 hours a day at school.",
     ["8:00", "13:00", "two shifts", "45 minutes"]),
    ("education", "edu", ["Gu-ch-33", "An-ar-09", "Jo-sp-43", "Al-en-19"],
     "In Azerbaijani schools English is taught from the early primary grades (about age 6-7), and Russian is the second most studied foreign language; students typically study 2-3 languages (Azerbaijani, English and Russian).",
     ["English", "Russian", "three languages", "age 6"]),
    ("education", "general", ["Ni-en-12", "New-in-62", "New-in-63"],
     "Top universities in Azerbaijan are Baku State University, ADA University, Azerbaijan Medical University (the leading medical school), Azerbaijan State Oil and Industry University and Baku Higher Oil School (known for engineering), Azerbaijan Technical University and UNEC (economics).",
     ["Baku State University", "ADA University", "Azerbaijan Medical University", "Oil and Industry University", "Baku Higher Oil School"]),
    ("education", "general", ["Ji-ko-38", "New-ch-72", "New-ch-31"],
     "Medicine is the hardest major to get into in Azerbaijan, followed by international relations, law and petroleum engineering; oil and gas engineering, IT and medicine are seen as most employable, and parents most often want their children to become doctors.",
     ["medicine", "doctor", "petroleum engineering", "law", "IT"]),
    ("education", "general", ["Al-en-18", "Ji-ko-35", "Ji-ko-36", "Th-en-51", "Al-en-21"],
     "Private tutoring (repetitor) is the most common form of private education in Azerbaijan, along with preparation courses (hazırlıq kursları) for the university entrance exam; the most tutored subjects are mathematics, English and Azerbaijani language, and mathematics is considered the most important subject.",
     ["repetitor", "tutor", "preparation courses", "mathematics", "English"]),
    ("education", "general", ["Ji-ko-37", "Ji-ko-41", "New-su-33"],
     "Azerbaijani school students must wear a school uniform (dark blue or black suit/skirt with a white shirt) and classic shoes; teachers wear formal business clothes.",
     ["school uniform", "white shirt", "classic shoes", "formal"]),
    ("education", "general", ["An-ar-02", "New-ch-74"],
     "Azerbaijani university students usually live with their families or rent apartments with friends; dormitories (yataqxana) are used by some students from the regions. They have lunch in the university canteen or nearby cafés and döner shops.",
     ["live with family", "rented apartment", "dormitory", "canteen"]),
    ("education", "general", ["Ji-ko-31", "Tmp-ar-01", "New-am-34", "Ji-ko-33"],
     "Azerbaijani students usually prepare for exams at home, in libraries or at their tutor's; in the evening high school students go to tutors or prep courses.",
     ["home", "library", "tutor"]),
    ("education", "general", ["Ji-ko-34", "Tmp-ar-02"],
     "Azerbaijani elementary pupils usually walk to school or are driven by their parents; university students in Baku commute by metro and bus.",
     ["walk", "parents' car", "metro", "bus"]),
    ("education", "general", ["New-ch-70"],
     "Common compulsory courses for all Azerbaijani university students include History of Azerbaijan, Azerbaijani language and speech culture, a foreign language, and philosophy.",
     ["History of Azerbaijan", "Azerbaijani language", "foreign language", "philosophy"]),
    ("education", "general", ["New-en-69"],
     "Writers commonly studied in Azerbaijani literature classes include Nizami Ganjavi, Fuzuli, Nasimi, Mirza Fatali Akhundov, Jalil Mammadguluzadeh, Mirza Alakbar Sabir, Huseyn Javid and Samad Vurgun.",
     ["Nizami Ganjavi", "Fuzuli", "Nasimi", "Sabir", "Samad Vurgun"]),
    ("education", "general", ["Th-en-48"],
     "Azerbaijani schools grade on a 5-point scale where 5 (\"əla\", excellent) is the highest mark.",
     ["5", "five", "ela", "grade"]),
    ("education", "general", ["Gu-ch-41", "Ji-ko-39", "New-su-34"],
     "The most commonly learned instruments by Azerbaijani children are the piano and the tar, usually in music schools; most children do not play an instrument at school.",
     ["piano", "tar", "music school"]),
    ("education", "general", ["Tmp-ar-04", "Ji-ko-40", "New-pe-66", "Th-en-53", "New-ch-73"],
     "After school Azerbaijani children do homework, go to tutors or sports clubs (football, wrestling, chess) and play outside. In breaks pupils chat, eat at the school buffet and use their phones. Popular university clubs are debate, volunteering and intellectual games (\"Nə? Harada? Nə zaman?\").",
     ["homework", "tutor", "sports clubs", "buffet", "debate", "intellectual games"]),
    ("education", "general", ["Al-en-17", "Jo-sp-32", "An-ar-34", "Na-ko-17", "Kik-in-45"],
     "Football is the most popular school sport in Azerbaijan; schools usually have a sports hall and a football pitch, and volleyball and basketball are also played in PE.",
     ["football", "volleyball", "sports hall", "school sport"]),
    ("education", "general", ["New-ch-71"],
     "Azerbaijani high school classes typically have about 25-30 students.",
     ["class size", "25", "30"]),
    ("education", "general", ["New-su-42"],
     "Azerbaijani state schools are secular and do not teach religion as a subject.",
     ["no religion", "secular"]),
    ("education", "general", ["Ji-ko-44"],
     "Baku is the centre of academic competition in Azerbaijan, with the most prestigious lyceums and universities.",
     ["Baku", "lyceum"]),
    ("education", "general", ["New-en-72"],
     "Azerbaijani students usually study online with YouTube, Google and online test platforms for exam preparation.",
     ["YouTube", "Google", "online tests"]),
    ("education", "general", ["New-pe-74", "New-ch-66"],
     "Public school education in Azerbaijan is free; at state universities students with high entrance scores study for free (state-funded places), others pay about 2,000-4,000 manat a year.",
     ["free", "state-funded", "manat", "tuition"]),

    # ---------------- sports ----------------
    ("sports", "sport", ["Gu-ch-08", "Gu-ch-06", "Jod-ch-38", "New-as-29", "Gu-ch-15", "Kik-in-34", "Th-en-03"],
     "Football (futbol) is the most popular sport in Azerbaijan to play and watch, especially among men and boys; the Azerbaijan Premier League and Qarabağ's European matches are the most watched, and many also follow Turkish clubs (Galatasaray, Fenerbahçe) and Real Madrid and Barcelona.",
     ["football", "futbol", "Premier League", "Qarabag", "Galatasaray"]),
    ("sports", "sport", ["Jo-sp-01", "New-pe-16", "Th-en-12", "Gu-ch-11", "Ta-pe-17", "Kik-in-44", "Kik-in-31"],
     "Wrestling (güləş), freestyle and Greco-Roman, is Azerbaijan's national sport and the sport in which it has won the most Olympic medals and international success, followed by judo, boxing and karate; it receives strong government support.",
     ["wrestling", "gules", "freestyle", "Greco-Roman", "judo", "Olympic medals"]),
    ("sports", "sport", ["Jo-sp-14", "Jo-sp-02"],
     "Chess (şahmat) is the most popular mental sport in Azerbaijan: world champion Garry Kasparov was born in Baku, and top grandmasters include Shakhriyar Mamedyarov and Teimour Radjabov; nard (backgammon) is also hugely popular.",
     ["chess", "shahmat", "Kasparov", "Mamedyarov", "Radjabov", "nard"]),
    ("sports", "general", ["An-ar-36", "Sa-en-16", "Kik-in-37", "Ta-pe-25", "Kik-in-36"],
     "Qarabağ FK, coached for many years by Gurban Gurbanov, is the most popular and successful football club in Azerbaijan; its biggest rivalry is with Neftçi PFK (Baku), and other clubs are Sabah, Zira, Sumgayit and Gabala.",
     ["Qarabag", "Neftchi", "Gurban Gurbanov", "derby"]),
    ("sports", "general", ["Th-en-11", "New-az-26", "Na-ko-19", "New-am-27", "New-en-23"],
     "Famous Azerbaijani athletes include wrestlers Toghrul Asgarov and Sharif Sharifov, judoka Elnur Mammadli and Hidayat Heydarov, karateka Rafael Aghayev, taekwondo champion Radik Isayev, volleyball players Natalya Mammadova and Polina Rahimova, and Paralympic judo champion Ilham Zakiyev.",
     ["Toghrul Asgarov", "Rafael Aghayev", "Elnur Mammadli", "Natalya Mammadova", "Ilham Zakiyev"]),
    ("sports", "general", ["Na-ko-16"],
     "Famous Azerbaijani football names include Anatoliy Banishevskiy (Neftçi legend), the referee Tofiq Bahramov (the national stadium is named after him), and modern players such as Rashad Sadygov and Mahir Emreli.",
     ["Banishevskiy", "Tofiq Bahramov", "Rashad Sadygov", "Mahir Emreli"]),
    ("sports", "sport", ["New-en-19", "Sa-en-22", "New-gr-29", "Th-en-09"],
     "Baku Olympic Stadium and Tofiq Bahramov Republican Stadium are Azerbaijan's best-known stadiums. Baku hosted the first European Games (2015), the 2017 Islamic Solidarity Games, Euro 2020 matches and the Formula 1 Azerbaijan Grand Prix on the Baku City Circuit.",
     ["Baku Olympic Stadium", "Tofiq Bahramov Stadium", "European Games", "Formula 1", "Baku City Circuit"]),
    ("sports", "general", ["An-ar-43"],
     "Azerbaijanis usually watch football at home, in tea houses (çayxana), cafés and pubs.",
     ["tea house", "chaykhana", "cafe", "home"]),
    ("sports", "general", ["Gu-ch-09", "Jod-ch-37", "New-as-30", "Na-ko-18", "Ta-pe-22", "New-as-20"],
     "Azerbaijani women most often do fitness/gym, walking, volleyball and rhythmic gymnastics (very popular for girls); volleyball, in which Azerbaijan's women's team is strong, is the most popular indoor team sport, and women commonly watch volleyball, gymnastics and football.",
     ["fitness", "volleyball", "rhythmic gymnastics", "walking", "women"]),
    ("sports", "general", ["Gu-ch-05", "Na-ko-26", "New-su-21", "Ta-pe-23"],
     "Older Azerbaijanis mostly walk (especially along the Baku Boulevard) and play nard, dominoes and chess in parks and tea houses; men commonly go to the gym or play football.",
     ["walking", "Boulevard", "nard", "domino", "gym"]),
    ("sports", "culture", ["New-ha-19", "New-pe-16"],
     "Chovgan, a traditional horse-riding polo game played with Karabakh horses (UNESCO-listed), is Azerbaijan's best-known traditional sport; the horse is the classic sports animal.",
     ["chovgan", "horse", "Karabakh horse", "polo"]),
    ("sports", "general", ["New-az-21", "Th-en-15", "Na-ko-28", "New-ch-26"],
     "The most popular ski resorts in Azerbaijan are Shahdag (Qusar) and Tufandag (Gabala); skiing is the main winter sport, and figure skating is the most watched Winter Olympic event.",
     ["Shahdag", "Tufandag", "Qusar", "Gabala", "skiing", "figure skating"]),
    ("sports", "general", ["Na-ko-23"],
     "Azerbaijani children most often attend football, wrestling, judo, chess and swimming academies; girls often do rhythmic gymnastics.",
     ["football", "wrestling", "chess", "swimming", "gymnastics"]),
    ("sports", "general", ["Na-ko-22"],
     "Armenia is considered Azerbaijan's biggest sporting rival for political reasons; the national team's colours follow the flag: blue, red and green.",
     ["Armenia", "rival", "blue", "red", "green"]),
    ("sports", "general", ["New-ch-27", "New-ch-23", "Na-ko-29"],
     "Famous Azerbaijani boxers include Magomedrasul Majidov (three-time amateur world champion) and Lorenzo Sotomayor (2016 Olympic silver).",
     ["Magomedrasul Majidov", "Lorenzo Sotomayor", "boxing"]),
    ("sports", "general", ["Ta-pe-21", "New-su-24", "New-su-17"],
     "Azerbaijani children play football in yards (həyət) between apartment blocks, on school pitches and in parks with mini-football fields; parents and children play football together.",
     ["yard", "football pitch", "park"]),
    ("sports", "general", ["New-gr-21", "Jo-sp-13", "Jo-sp-09", "New-pe-20"],
     "Tennis and table tennis are the most played racket sports in Azerbaijan; swimming is the most popular water sport, beach football and volleyball are played on the Caspian beaches, and tennis, golf and horse riding are associated with the upper class.",
     ["tennis", "table tennis", "swimming", "beach football", "golf"]),
    ("sports", "general", ["Ta-pe-29"],
     "Football is the highest-paying professional sport in Azerbaijan.",
     ["football", "highest paying"]),
    ("sports", "general", ["New-en-17", "New-en-18"],
     "Azerbaijani football fans bring flags, scarves and drums to games.",
     ["flags", "scarves", "drums"]),

    # ---------------- holidays / celebrations / leisure ----------------
    ("holidays_celebrations_leisure", "hol", ["Jod-ch-16", "Kik-in-01", "Ne-ar-05", "Jod-ch-30"],
     "Novruz Bayramı, the spring New Year (20-24 March, 5 days off), is the biggest and longest holiday in Azerbaijan. Its symbols are səməni (green wheat sprouts), the xonça tray with sweets, candles and painted eggs, bonfires that people jump over, and the four pre-holiday Tuesdays (water, fire, wind and earth).",
     ["Novruz", "semeni", "khoncha", "bonfire", "painted eggs", "five days"]),
    ("holidays_celebrations_leisure", "culture", ["Na-ko-33", "Kik-in-07", "Ta-pe-45"],
     "Symbolic Novruz foods are plov, shekerbura, pakhlava, shorgoghal and painted eggs; children throw hats or bags at neighbours' doors (papaq atmaq) and receive sweets.",
     ["Novruz", "shekerbura", "pakhlava", "shorgoghal", "plov", "sweets"]),
    ("holidays_celebrations_leisure", "general", ["Al-en-34", "Ne-ar-11", "Ca-sp-29", "Ta-pe-42", "Ta-pe-37", "Ta-pe-32"],
     "On New Year's Eve (31 December) Azerbaijanis decorate a New Year tree (yolka), children wait for Şaxta Baba (Father Frost) and Qar Qız (Snow Maiden), families eat Olivier salad, plov and sweets with champagne, and fireworks are set off at midnight, especially on the Baku Boulevard.",
     ["New Year tree", "Shakhta Baba", "Olivier salad", "champagne", "fireworks", "December 31"]),
    ("holidays_celebrations_leisure", "hol", ["Ne-ar-14", "New-su-77", "New-ch-80", "New-am-77"],
     "Ramazan Bayramı and Qurban Bayramı (2 days off each) are the main religious holidays in Azerbaijan; families visit relatives and cemeteries, children receive sweets and money, and people visit mosques and shrines during Bayrams and Muharram (Ashura).",
     ["Ramazan Bayrami", "Qurban Bayrami", "mosque", "sweets", "money"]),
    ("holidays_celebrations_leisure", "culture", ["Kik-in-06", "Na-ko-38", "Na-ko-39"],
     "Azerbaijani weddings follow matchmaking (elçilik) and engagement (nişan), with a henna night (xına yaxdı) before the wedding. Guests give money in envelopes as a wedding gift; between bride and groom gold jewellery and a ring are the usual gifts.",
     ["elchilik", "nishan", "henna night", "money", "gold"]),
    ("holidays_celebrations_leisure", "culture", ["New-su-81", "New-su-82", "New-ch-84", "New-ch-82"],
     "An Azerbaijani bride wears a white wedding dress with a red ribbon tied at her waist by her brother, and the groom wears a black suit; guests wear formal evening clothes. Weddings usually start in the evening around 18:00-19:00.",
     ["white dress", "red ribbon", "black suit", "evening", "18:00"]),
    ("holidays_celebrations_leisure", "culture", ["Kik-in-04", "Na-ko-40", "Na-ko-41", "Na-ko-42", "New-gr-88", "New-ch-85", "New-ko-07"],
     "When someone dies in Azerbaijan a mourning tent (yas çadırı) is set up in front of the house; mourning lasts three days, with memorials on the 7th and 40th days and on Thursdays. Mourners wear black, give money, and are served unsweetened tea, halva, dates and plov.",
     ["mourning tent", "three days", "40th day", "black", "halva", "tea"]),
    ("holidays_celebrations_leisure", "general", ["New-am-81"],
     "Most Azerbaijani weddings take place in summer and autumn (especially August-October); weddings are avoided during Ramadan and Muharram.",
     ["summer", "autumn", "August", "September", "wedding season"]),
    ("holidays_celebrations_leisure", "culture", ["New-am-83", "New-gr-82", "New-su-88"],
     "The tar is the most popular traditional Azerbaijani instrument, along with the kamancha, balaban, saz and naghara. Older people love mugham and folk music; young people listen to pop, Turkish pop, rap and meykhana.",
     ["tar", "kamancha", "balaban", "mugham", "pop"]),
    ("holidays_celebrations_leisure", "culture", ["New-as-80", "New-as-89"],
     "Traditional Azerbaijani festival clothing includes the arkhalig (long coat) and papakha (sheepskin hat) for men and long dresses with the kelaghayi silk headscarf (UNESCO-listed) for women.",
     ["arkhalig", "papakha", "kelaghayi", "national costume"]),
    ("holidays_celebrations_leisure", "general", ["Kik-in-10", "New-en-87", "New-pe-86", "Kik-in-11"],
     "The most famous landmarks in Azerbaijan are the Maiden Tower (Qız Qalası) and the Old City (İçərişəhər) of Baku with the Palace of the Shirvanshahs, the Flame Towers, the Heydar Aliyev Center, Gobustan rock art, Yanar Dag and the Ateshgah fire temple; Bibi-Heybat Mosque is the main religious site for visitors.",
     ["Maiden Tower", "Old City", "Flame Towers", "Heydar Aliyev Center", "Gobustan", "Bibi-Heybat"]),
    ("holidays_celebrations_leisure", "general", ["New-su-86", "New-en-90", "New-en-76", "New-in-80", "New-ch-83"],
     "Government House (Hökumət Evi) is Azerbaijan's best-known government building; famous hotels include the Fairmont Baku (Flame Towers), Hilton Baku and JW Marriott Absheron; Heydar Aliyev International Airport is the busiest airport, and Baku hosts most festivals.",
     ["Government House", "Fairmont", "Hilton Baku", "Heydar Aliyev International Airport", "Baku"]),
    ("holidays_celebrations_leisure", "general", ["New-in-78"],
     "Bank cards and cash are the main payment methods in Azerbaijan; mobile banking apps such as Birbank are widely used.",
     ["bank card", "cash", "Birbank"]),
    ("holidays_celebrations_leisure", "general", ["Jod-ch-41", "Jod-ch-42", "New-ch-78", "New-ch-79", "New-pe-76"],
     "Young Azerbaijani women spend leisure time in cafés, shopping malls, at the gym and on Instagram; young men play football, go to the gym, play nard and meet in cafés or tea houses. Retired men play nard and dominoes in tea houses and parks; retired women visit relatives and neighbours and watch TV series. People walk and cycle in parks and along the Boulevard.",
     ["cafe", "shopping", "gym", "nard", "domino", "tea house"]),
    ("holidays_celebrations_leisure", "general", ["Jod-ch-28"],
     "Azerbaijanis travel between cities mainly by intercity bus and minibus, by train, or by car.",
     ["bus", "train", "car"]),
    ("holidays_celebrations_leisure", "hol", ["Al-en-38", "Ni-en-37"],
     "Valentine's Day (14 February) is celebrated in Azerbaijan with flowers (red roses), chocolates and gifts; 8 March (Women's Day) is a public holiday when women receive flowers.",
     ["Valentine's Day", "roses", "March 8", "flowers"]),

    # ---------------- work life ----------------
    ("work_life", "labour", ["Ni-en-17", "Jod-ch-60", "Ji-ko-08", "Ni-en-19", "Ne-ar-16"],
     "The standard working week in Azerbaijan is 40 hours over 5 days (8 hours a day, Monday to Friday); Saturday and Sunday are the weekend.",
     ["40 hours", "8 hours", "five days", "Saturday", "Sunday"]),
    ("work_life", "general", ["Ne-ar-17", "Ne-ar-18", "Ki-pe-51", "Ki-pe-53", "Jo-sp-21", "Ji-ko-15", "Jod-ch-46"],
     "Azerbaijani offices and government agencies usually work from 9:00 to 18:00 with a one-hour lunch break from 13:00 to 14:00.",
     ["9:00", "18:00", "13:00", "one hour", "lunch break"]),
    ("work_life", "labour", ["Jo-sp-18", "Jod-ch-54"],
     "Azerbaijani employees get at least 21 calendar days of paid annual leave (30 days for teachers, doctors and civil servants); marriage leave is short and not fixed by law.",
     ["21 days", "annual leave", "30 days"]),
    ("work_life", "labour2", ["Jod-ch-56", "Jod-ch-57", "New-ch-44", "Ni-en-21", "Ni-en-20"],
     "The retirement age in Azerbaijan is 65 for men, and for women it is rising to 65 (63 until recently). Probation for new employees lasts up to three months. Employment is allowed from age 15, and most people start working after university at about 22.",
     ["retirement age", "65", "63", "three months", "15"]),
    ("work_life", "general", ["Jod-ch-51", "Jod-ch-50"],
     "In Baku people commute by metro, BakuBus city buses and private cars (and taxis via Bolt/Uber); commutes typically take 30-60 minutes because of traffic.",
     ["metro", "bus", "car", "taxi", "Bolt"]),
    ("work_life", "general", ["Ne-ar-20", "Jod-ch-58", "Jod-ch-61", "Jod-ch-62", "Ne-ar-25", "New-gr-58"],
     "Government (state) jobs and jobs at SOCAR are seen as the most secure in Azerbaijan. Doctors and teachers are the most respected professions; women often prefer teaching and medicine, men engineering, the oil industry, and business. The oil and gas industry, banking and IT pay best, while teachers are considered underpaid.",
     ["government job", "SOCAR", "doctor", "teacher", "oil and gas"]),
    ("work_life", "economy", ["Ne-ar-26", "Th-en-27", "Ji-ko-14"],
     "SOCAR (State Oil Company of Azerbaijan Republic) is the most famous public corporation; oil and gas are the most important industry, about two-thirds of GDP and 90% of export revenue, through the Azeri-Chirag-Gunashli and Shah Deniz fields and the Baku-Tbilisi-Ceyhan pipeline.",
     ["SOCAR", "oil", "gas", "Shah Deniz", "BTC pipeline"]),
    ("work_life", "economy", ["Ji-ko-07", "New-en-41"],
     "Well-known private companies in Azerbaijan include Azersun Holding, PASHA Holding, Azercell, Bakcell and Kapital Bank.",
     ["Azersun", "PASHA Holding", "Azercell", "Bakcell"]),
    ("work_life", "general", ["Ne-ar-24", "Ji-ko-03", "Nu-in-40", "Th-en-24", "New-ch-38"],
     "Baku is Azerbaijan's commercial and financial hub, the main destination for job seekers, the centre for tech start-ups, and the main import/export centre through the Port of Baku at Alat.",
     ["Baku", "commercial hub", "Port of Baku", "Alat"]),
    ("work_life", "economy", ["Th-en-19", "New-in-33", "New-in-34"],
     "Sumgait is Azerbaijan's main manufacturing city (chemical industrial park), with Ganja another industrial centre. Mining is centred in Dashkasan (iron ore) and Gadabay (gold, copper); oil is associated with Baku, the Absheron peninsula and the Caspian Sea.",
     ["Sumgait", "Ganja", "Dashkasan", "Gadabay", "Absheron", "Caspian"]),
    ("work_life", "economy", ["New-am-53", "Jo-sp-19", "New-am-54"],
     "Lankaran-Astara is Azerbaijan's tea and citrus region; Guba-Khachmaz is known for apples, Sheki-Zagatala for hazelnuts, and the Aran lowlands (Kur-Araz) for cotton, grain and livestock. Highland pastures are used for sheep herding.",
     ["Lankaran", "tea", "Guba", "Sheki", "Aran", "cotton"]),
    ("work_life", "economy", ["Th-en-22"],
     "Azerbaijan's most catastrophic economic period was the early 1990s, after the collapse of the Soviet Union and during the Karabakh war; the 2015 manat devaluation was another crisis.",
     ["1990s", "Soviet collapse", "2015 devaluation"]),
    ("work_life", "general", ["New-su-50", "New-su-51", "New-am-59", "New-am-60", "New-su-57", "New-su-58"],
     "In Azerbaijan's mountain areas people mainly do livestock (sheep) herding, beekeeping and fruit growing; in coastal areas fishing, tourism and the oil industry. Sheep are the most common livestock, followed by cattle; horses and donkeys are used for transport in villages, and oxen and buffalo for farm work.",
     ["sheep", "livestock", "fishing", "horse", "donkey", "oxen"]),
    ("work_life", "general", ["New-su-59", "New-su-60"],
     "Azerbaijani farmers wear caps or straw hats and headscarves in the heat, and usually eat bread, cheese, herbs, vegetables and tea for lunch.",
     ["cap", "hat", "headscarf", "bread", "cheese"]),
    ("work_life", "general", ["Th-en-21", "Ji-ko-02", "New-ko-09"],
     "Valued employee perks in Azerbaijan are health insurance, free lunch and transport; corporate events are usually restaurant dinners with kebab and plov, and team-building trips to Gabala or Guba.",
     ["health insurance", "lunch", "restaurant", "Gabala"]),
    ("work_life", "general", ["New-ko-10", "New-ko-08", "New-ch-45", "New-ch-39"],
     "Common side jobs in Azerbaijan are taxi driving (Bolt, Uber), private tutoring and selling online via Instagram; students work part-time in cafés, shops and call centres. Young people start businesses in IT, cafés and online retail; Tap.az, Umico and Trendyol are popular e-commerce platforms.",
     ["taxi", "tutoring", "Instagram", "Tap.az", "Umico", "Trendyol"]),
    ("work_life", "general", ["New-az-49"],
     "In a typical Azerbaijani family one or two people work, often the father and increasingly both parents.",
     ["one", "two", "father"]),
    ("work_life", "general", ["New-pe-45"],
     "Azerbaijan is secular, and the work schedule does not change during Ramadan.",
     ["Ramadan", "no change"]),
    ("work_life", "general", ["New-ch-32"],
     "Microsoft Office (Word, Excel) is the standard office software in Azerbaijani workplaces.",
     ["Microsoft Office", "Excel", "Word"]),
]
