"""Ethiopia KB v2: question-driven everyday-knowledge cards (English, with Amharic terms).

Each card: (category, source_key, written_for_question_ids, text_en, keywords).
Written from the BLEnD *question types* plus the cited sources; gold answers were not consulted.
"""

SOURCES = {
    "cuisine": ("Ethiopian cuisine", "Wikipedia", "https://en.wikipedia.org/wiki/Ethiopian_cuisine", "high"),
    "edu": ("Education in Ethiopia", "Wikipedia", "https://en.wikipedia.org/wiki/Education_in_Ethiopia", "high"),
    "hol": ("Public holidays in Ethiopia", "Wikipedia", "https://en.wikipedia.org/wiki/Public_holidays_in_Ethiopia", "high"),
    "sport": ("Sport in Ethiopia", "Wikipedia", "https://en.wikipedia.org/wiki/Sport_in_Ethiopia", "high"),
    "labour": ("Labour Proclamation No. 1156/2019", "Federal Negarit Gazette (Ethiopia)",
               "https://www.metaappz.com/References/ethiopian_laws/federal/pr_1156_2019/en/txt", "high"),
    "derby": ("St. George, Ethiopia Coffee face-off in Sheger Derby", "The Reporter Ethiopia",
              "https://www.thereporterethiopia.com/5095/", "high"),
    "wedding": ("Ethiopia: Wedding extravaganzas as if there is no tomorrow", "allAfrica / The Ethiopian Herald",
                "https://allafrica.com/stories/202401240366.html", "medium"),
    "culture": ("Culture of Ethiopia", "Wikipedia", "https://en.wikipedia.org/wiki/Culture_of_Ethiopia", "high"),
    "economy": ("Economy of Ethiopia", "Wikipedia", "https://en.wikipedia.org/wiki/Economy_of_Ethiopia", "high"),
    "general": ("Ethiopia (compiled general reference)", "Wikipedia and general reference",
                "https://en.wikipedia.org/wiki/Ethiopia", "medium"),
}

CARDS = [
    # ---------------- food ----------------
    ("food", "cuisine", ["Ne-ar-31", "New-am-02", "New-pe-06", "Th-en-44"],
     "The most famous Ethiopian food is injera (እንጀራ), a large spongy sourdough flatbread made from fermented teff, eaten with wat (stew). Doro wat (ዶሮ ወጥ), a spicy chicken stew with boiled eggs and berbere, is considered the national dish; shiro, key wat (beef stew), misir wat (lentils), tibs and kitfo are also very popular.",
     ["injera", "doro wat", "teff", "shiro", "national dish"]),
    ("food", "cuisine", ["Ne-ar-34", "Na-ko-09", "Ca-sp-08"],
     "Injera is indispensable in almost every Ethiopian meal and also serves as the plate and the spoon. The most common ingredients of Ethiopian cooking are teff, berbere (በርበሬ, chili spice mix), onion, garlic and niter kibbeh (spiced clarified butter).",
     ["injera", "teff", "berbere", "onion", "niter kibbeh"]),
    ("food", "cuisine", ["Ne-ar-32", "New-gr-05", "Th-en-35"],
     "Typical Ethiopian breakfasts are firfir/fitfit (shredded injera or kitcha in spicy sauce), chechebsa (kita firfir), genfo (thick porridge with butter and berbere), kinche (cracked wheat or barley), fatira (fried pancake with egg), ful (fava beans) and bread (dabo) with tea or coffee.",
     ["firfir", "chechebsa", "genfo", "kinche", "ful", "breakfast"]),
    ("food", "cuisine", ["Ca-sp-14", "New-gr-13", "Na-ko-02", "New-as-05", "New-as-58", "Ki-pe-34"],
     "Coffee (buna, ቡና) is the most popular drink in Ethiopia, the birthplace of coffee. It is served to guests in the traditional coffee ceremony: beans are roasted, ground and boiled in a jebena clay pot and served in three rounds (abol, tona, bereka). Tea (shai, ሻይ) and macchiato are also very common, including at breakfast and at the workplace.",
     ["coffee", "buna", "coffee ceremony", "jebena", "tea", "macchiato"]),
    ("food", "cuisine", ["Ne-ar-44", "Ne-ar-43"],
     "In Ethiopia coffee is usually accompanied by popcorn (fendisha) or kolo (roasted barley), and sometimes bread (dabo); tea is commonly taken with bread, dabo kolo or biscuits.",
     ["popcorn", "kolo", "bread", "dabo", "coffee"]),
    ("food", "cuisine", ["Al-en-01", "Sa-en-7", "New-su-01", "Al-en-08", "Al-en-09", "New-en-01", "New-ch-04"],
     "Popular snacks in Ethiopia are kolo (ቆሎ, roasted barley with chickpeas and peanuts), dabo kolo (small crunchy fried dough bites), popcorn, sambusa (lentil- or meat-filled pastry), biscuits, roasted corn (yebekolo tibs), peanuts and chips; sellers in front of schools sell kolo, biscuits, candy and sambusa.",
     ["kolo", "dabo kolo", "popcorn", "sambusa", "biscuits", "roasted corn"]),
    ("food", "cuisine", ["Al-en-02", "New-ch-07", "Ji-ko-09"],
     "Beer and spirits in Ethiopia are usually accompanied by meat: tibs (sautéed beef or lamb), kitfo, raw meat (tere siga), as well as kolo, peanuts or chips.",
     ["tibs", "kitfo", "raw meat", "beer", "kolo"]),
    ("food", "general", ["Al-en-04", "New-az-11", "Na-ko-08", "Ne-ar-37", "New-ch-54"],
     "The most popular fruits in Ethiopia are banana (ሙዝ), orange (ብርቱካን), mango, avocado and papaya; mango and avocado are abundant in season, and layered avocado-mango-papaya juice (spris) is a favourite café drink.",
     ["banana", "orange", "mango", "avocado", "papaya", "fruit"]),
    ("food", "cuisine", ["Al-en-06", "Jod-ch-48", "New-su-60", "New-en-05", "Ne-ar-39"],
     "Common everyday lunches in Ethiopia (school, work and farm) are injera with shiro (ሽሮ, chickpea-flour stew), misir wat (lentils) or beyaynetu (mixed fasting platter); pasta and bread are also common. Shiro and pasta are the cheapest quick meals; farmers often eat kitta bread, kolo or injera with shiro.",
     ["shiro", "injera", "beyaynetu", "pasta", "lunch"]),
    ("food", "general", ["Ca-sp-05", "Ca-sp-06", "Ca-sp-11"],
     "Ethiopians usually eat three meals a day (breakfast, lunch and dinner). Sunday, after church, is the usual day for a big family meal.",
     ["three meals", "Sunday", "family meal"]),
    ("food", "cuisine", ["Ca-sp-09", "New-gr-15", "New-spme-05"],
     "Dessert is not a traditional course in Ethiopian meals; a meal usually ends with coffee or fruit. Popular sweets are cake, baklava, halawa (sesame/peanut sweet), candy and dabo kolo.",
     ["dessert", "fruit", "coffee", "cake", "halawa"]),
    ("food", "cuisine", ["Jod-ch-01", "New-ha-09"],
     "Ethiopians traditionally eat with their right hand, tearing pieces of injera to pick up food instead of using cutlery, often from a shared platter or mesob basket. The mitad (clay griddle) is the main utensil for baking injera, and the jebena clay pot is used for coffee.",
     ["hand", "right hand", "injera", "mitad", "mesob", "jebena"]),
    ("food", "general", ["Jod-ch-04", "New-spme-68", "New-as-15"],
     "Popular soft drinks in Ethiopia are Coca-Cola, Pepsi, Mirinda, Fanta and Sprite, and the carbonated mineral water Ambo; in hot weather people drink cold water, soft drinks, Ambo water and fresh juices.",
     ["Coca-Cola", "Pepsi", "Mirinda", "Ambo water", "soft drink"]),
    ("food", "cuisine", ["Jod-ch-06", "New-gr-89", "New-gr-08", "New-az-69", "New-az-70", "Ca-sp-19"],
     "Traditional Ethiopian alcoholic drinks are tej (ጠጅ, honey wine), tella (ጠላ, home-brewed barley beer) and areke (distilled spirit). Tej and tella are served at weddings and holidays. Men commonly drink beer, areke or whisky; women more often prefer tej, wine or beer.",
     ["tej", "tella", "areke", "honey wine", "beer"]),
    ("food", "general", ["New-ch-13", "New-az-05"],
     "Popular Ethiopian beer brands are St. George (the oldest, Addis Ababa), Habesha, Walia, Meta, Dashen (Gondar), Bedele and Harar beer; Awash and Castel make Ethiopian wine.",
     ["St. George beer", "Habesha", "Walia", "Meta", "Dashen", "Bedele"]),
    ("food", "general", ["Jod-ch-09", "Ne-ar-33", "New-ch-02"],
     "Typical Ethiopian mealtimes: breakfast around 7:00-8:00, lunch around 12:30-13:00 and dinner around 19:00-20:00.",
     ["breakfast", "lunch", "dinner", "meal times"]),
    ("food", "general", ["Jod-ch-12", "New-ch-09", "New-as-14"],
     "Soups common in Ethiopia are lentil soup, vegetable soup, meat/bone broth (shorba) and pasta soup. In cold or rainy weather people prefer hot drinks (coffee, tea), roasted corn, kolo, genfo and soup.",
     ["soup", "shorba", "lentil soup", "roasted corn"]),
    ("food", "general", ["Jod-ch-13", "Sa-en-6", "New-gr-06", "Na-ko-05", "New-en-12"],
     "Popular street, takeaway and youth foods in Ethiopian cities are sambusa, chips (French fries), burgers, pizza, shawarma, ful and egg sandwiches; pizza and burgers are favourites among young people.",
     ["sambusa", "chips", "burger", "pizza", "shawarma", "ful"]),
    ("food", "general", ["New-in-01", "Sa-en-1"],
     "The best-known Ethiopian coffee shop chains are Kaldi's Coffee and Tomoca; international fast-food chains are rare in Ethiopia, and local burger and pizza restaurants dominate.",
     ["Kaldi's Coffee", "Tomoca", "coffee shop"]),
    ("food", "general", ["Jod-ch-15", "New-as-07", "New-az-12"],
     "Ethiopia is landlocked; fish (mainly tilapia and Nile perch) comes from lakes such as Lake Tana (Bahir Dar), Lake Hawassa, Lake Ziway and Arba Minch. Fried fish (asa tibs), fish goulash and fish dulet are eaten especially during fasting periods.",
     ["fish", "tilapia", "Lake Tana", "Hawassa", "Bahir Dar", "Arba Minch"]),
    ("food", "cuisine", ["Ki-pe-32", "Ne-ar-36", "New-su-83", "Ji-ko-09"],
     "For guests, holidays and weddings Ethiopians prepare doro wat with injera, raw meat (tere siga), kitfo and tibs, and serve coffee, tej or tella. Doro wat is the typical festive meal.",
     ["doro wat", "raw meat", "kitfo", "tibs", "festive meal"]),
    ("food", "cuisine", ["Ki-pe-36", "New-in-03", "New-ha-07"],
     "Because of the Italian occupation, Italian food (pasta, pizza, lasagna) is the most popular foreign cuisine in Ethiopia. Abroad, Ethiopian restaurants serve injera with wat, and Ethiopia gave the world coffee.",
     ["Italian food", "pasta", "pizza", "coffee", "injera"]),
    ("food", "cuisine", ["Ki-pe-40", "Sa-en-13", "New-ha-08"],
     "Raw-meat dishes such as kitfo, tere siga and gored gored are considered strange or disgusting by many foreigners and are divisive; the sour taste of injera is also divisive. Elderly people especially enjoy raw meat and traditional foods.",
     ["raw meat", "kitfo", "tere siga", "gored gored", "injera"]),
    ("food", "cuisine", ["Ki-pe-43", "New-as-02"],
     "Popular breads in Ethiopia are dabo (ዳቦ, wheat bread), ambasha (slightly sweet celebration bread), defo dabo (baked in leaves) and kitcha (unleavened flatbread). Bread and pasta (macaroni) are the most common wheat-based foods.",
     ["dabo", "bread", "ambasha", "kitcha", "pasta"]),
    ("food", "general", ["Kik-in-24"],
     "In Ethiopian fast-food restaurants chicken is usually served with French fries (chips) or rice.",
     ["chips", "French fries", "rice", "chicken"]),
    ("food", "cuisine", ["Na-ko-07", "New-ch-01"],
     "Beef is the most consumed meat in Ethiopia, followed by lamb/mutton, goat and chicken; Orthodox Christians and Muslims avoid pork. Grilled or sautéed beef or lamb (tibs) is the usual barbecue-style dish.",
     ["beef", "lamb", "mutton", "goat", "chicken", "tibs"]),
    ("food", "general", ["Na-ko-11", "Na-ko-24"],
     "While watching football Ethiopians snack on popcorn, kolo, peanuts and sambusa, and drink beer or soft drinks.",
     ["popcorn", "kolo", "peanuts", "beer", "football"]),
    ("food", "cuisine", ["Na-ko-15", "New-ch-14", "New-am-15", "New-su-10"],
     "Nourishing foods in Ethiopia: genfo (ገንፎ, thick barley or wheat porridge with spiced butter and berbere) and atmit (thin barley-oat drink) are given to new mothers after childbirth and to the sick; chicken soup, kinche and eggs are also given. Pregnant women are encouraged to eat milk, eggs, fruits and vegetables.",
     ["genfo", "atmit", "porridge", "chicken soup", "childbirth"]),
    ("food", "general", ["Ne-ar-38"],
     "Food given as charity in Ethiopia (for example outside churches and at religious feasts) is usually bread (dabo), injera and kolo, and meat at Eid.",
     ["charity", "bread", "injera", "kolo"]),
    ("food", "cuisine", ["New-am-04", "New-ch-08", "New-pe-11", "New-ch-05"],
     "The indispensable seasonings in Ethiopian cooking are berbere (chili spice blend), mitmita (hot birdseye-chili powder), niter kibbeh (spiced butter), onion, garlic, ginger and korarima. Awaze (berbere paste) and mitmita are the most popular dips; the most famous spicy dishes are doro wat, key wat and kitfo with mitmita.",
     ["berbere", "mitmita", "awaze", "niter kibbeh", "spicy"]),
    ("food", "cuisine", ["New-am-08"],
     "During Orthodox Christian fasting (Lent/Abiy Tsom and every Wednesday and Friday) Ethiopians eat vegan food: shiro, misir wat (lentils), kik alicha (split peas), gomen (collard greens), atkilt (cabbage, potato, carrot) and beyaynetu.",
     ["fasting", "shiro", "misir wat", "gomen", "beyaynetu", "vegan"]),
    ("food", "economy", ["New-as-01", "New-spme-04", "Ji-ko-14"],
     "Ethiopia's main crops are teff, maize, wheat, sorghum and barley. Coffee is the country's largest export, followed by oilseeds (sesame), khat, cut flowers, pulses and gold.",
     ["coffee", "teff", "maize", "sesame", "khat", "export"]),
    ("food", "general", ["New-en-04", "New-en-07"],
     "The best-known chef of Ethiopian origin is Marcus Samuelsson, an Ethiopian-born Swedish-American celebrity chef.",
     ["Marcus Samuelsson", "chef"]),
    ("food", "cuisine", ["New-en-10"],
     "The most eaten cheese in Ethiopia is ayib (አይብ), a mild crumbly fresh cottage cheese served with spicy dishes and kitfo.",
     ["ayib", "cheese", "cottage cheese"]),
    ("food", "general", ["New-ha-13", "New-en-11"],
     "Common vegetables in Ethiopia are potatoes, cabbage, onions, carrots, tomatoes and collard greens (gomen).",
     ["potato", "cabbage", "onion", "carrot", "gomen"]),
    ("food", "general", ["New-pe-02"],
     "The most typical edible souvenirs from Ethiopia are coffee beans, berbere and mitmita spice, honey and tej.",
     ["coffee", "berbere", "souvenir", "honey"]),
    ("food", "cuisine", ["New-su-09", "New-su-15"],
     "Ethiopians cook with vegetable oil (sunflower, palm or nug/niger-seed oil) and niter kibbeh butter. Traditional non-alcoholic drinks are keribo/kenetto (barley drink), borde, atmet and coffee.",
     ["vegetable oil", "niter kibbeh", "keribo", "borde"]),
    ("food", "general", ["Kik-in-17", "Ne-ar-06", "Ne-ar-09", "Ne-ar-10"],
     "During Ramadan Ethiopian Muslims break the fast with dates, sambusa, soup and fruit. At Eid al-Fitr and Eid al-Adha they eat doro wat, meat dishes and sweets; at Eid al-Adha a sheep or ox is slaughtered and the meat shared.",
     ["Ramadan", "dates", "sambusa", "Eid", "doro wat"]),
    ("food", "general", ["Ki-pe-39", "Sa-en-9", "New-ch-15"],
     "For picnics and trips Ethiopians take bread, injera rolls with firfir or dulet, sambusa, kolo, fruit and soft drinks.",
     ["picnic", "bread", "sambusa", "kolo"]),

    # ---------------- family ----------------
    ("family", "general", ["Ca-sp-38"],
     "In Ethiopian cities families typically live in condominium apartments or compound houses (gibi) behind a fence; in rural areas the traditional house is the round thatched hut (tukul).",
     ["condominium", "compound house", "tukul", "house"]),
    ("family", "general", ["Ca-sp-41", "New-az-60", "New-pe-59"],
     "In Ethiopia elderly parents usually live with their children and family; nursing homes are rare. When both parents work, children are cared for by grandparents, relatives or a housemaid (nanny). Households often have two or three generations.",
     ["elderly", "family", "grandparents", "housemaid", "nanny"]),
    ("family", "labour", ["Ca-sp-42", "Ca-sp-43"],
     "Ethiopian law (Labour Proclamation 1156/2019) gives mothers 120 days of paid maternity leave (30 days before and 90 days after birth, about 17 weeks) and fathers 3 days of paid paternity leave.",
     ["maternity leave", "120 days", "paternity leave", "3 days"]),
    ("family", "general", ["Gu-ch-16", "Gu-ch-18", "Ta-pe-13"],
     "The average Ethiopian household has about 5 members. Couples today typically have 3-4 children (fewer, 2-3, in cities); in the parents' generation families were larger, often 6-8 children.",
     ["household size", "children", "family size"]),
    ("family", "general", ["Ji-ko-16", "Ji-ko-28"],
     "After childbirth an Ethiopian mother traditionally rests for about 40 days, often at her own mother's home, and is fed genfo and atmit. In the Orthodox tradition boys are baptised (kristina) on the 40th day and girls on the 80th day.",
     ["40 days", "childbirth", "baptism", "kristina"]),
    ("family", "general", ["Ji-ko-29", "Al-en-39", "New-spme-78", "New-su-71"],
     "Birthdays in Ethiopian cities are celebrated with a cake and the song \"Happy Birthday\" (Melkam Lidet); the first birthday is often the most celebrated. Children usually receive clothes, toys or money as gifts.",
     ["birthday", "cake", "Happy Birthday", "Melkam Lidet"]),
    ("family", "hol", ["Ji-ko-25", "New-as-64", "Th-en-38"],
     "Families in Ethiopia reunite at major holidays: Fasika (Easter), Genna (Christmas), Meskel, Enkutatash (New Year) and Eid. Fasika and Meskel are among the biggest family gatherings.",
     ["Fasika", "Easter", "Genna", "Meskel", "Enkutatash", "Eid"]),
    ("family", "general", ["Ji-ko-27", "Ji-ko-22", "New-pe-53", "New-pe-54"],
     "When visiting elderly parents Ethiopians often bring coffee, sugar, bread, clothing (such as a gabi or netela shawl) or money; a first salary is traditionally spent on gifts for parents, especially clothes for the mother.",
     ["gift", "parents", "clothes", "netela", "gabi", "money"]),
    ("family", "general", ["Ji-ko-24", "Al-en-40", "Th-en-36"],
     "Popular places for families with children in Addis Ababa are parks and playgrounds such as Unity Park, Entoto Park and Friendship Park, and play areas in malls (e.g. Edna Mall). On weekends families go to church, visit relatives, go to parks or have picnics.",
     ["Unity Park", "Entoto Park", "Friendship Park", "playground", "park"]),
    ("family", "general", ["New-am-73", "New-am-72", "New-am-74", "New-ko-01", "Sa-en-32"],
     "Popular TV in Ethiopia includes EBS TV's talk show \"Seifu on EBS\" (host Seifu Fantahun) and dubbed foreign drama series on Kana TV; the educational children's programme \"Tsehai Loves Learning\" was popular with kids.",
     ["Seifu on EBS", "EBS", "Kana TV", "Tsehai"]),
    ("family", "general", ["New-ch-49"],
     "Ethiopian families communicate remotely mostly by phone calls and by Telegram, which is the most widely used messaging app in Ethiopia, along with IMO, WhatsApp and Facebook.",
     ["Telegram", "phone call", "IMO", "WhatsApp"]),
    ("family", "general", ["Ca-sp-45", "New-ch-51", "Na-ko-37", "Na-ko-45"],
     "Popular domestic family and honeymoon destinations in Ethiopia are lake resorts such as Bishoftu (Debre Zeit, Kuriftu resort), Hawassa, Bahir Dar (Lake Tana), Lake Langano, Sodere hot springs and Arba Minch; families usually book hotels or resorts.",
     ["Bishoftu", "Hawassa", "Bahir Dar", "Langano", "Sodere", "resort"]),
    ("family", "general", ["New-en-47"],
     "Ethiopian house compounds commonly have a garden with enset (false banana), vegetables such as gomen, fruit trees, chickens and sometimes a coffee plant.",
     ["garden", "enset", "chickens", "vegetables"]),
    ("family", "general", ["New-en-49", "New-en-50"],
     "Ethiopians do not use family surnames; a person's second name is the father's given name. Common names include Tesfaye, Mohammed, Getachew, Alemu and Abebe. The most famous family is the imperial family of Emperor Haile Selassie (Solomonic dynasty).",
     ["surname", "father's name", "Haile Selassie", "Tesfaye", "Mohammed"]),
    ("family", "culture", ["New-en-55", "New-pe-49", "New-spme-60"],
     "Most Ethiopians are Christian (about 63%, mostly Ethiopian Orthodox Tewahedo, plus Protestants) and about a third are Muslim. Christian families pray together at church on Sundays; Muslim families go to the mosque, especially on Fridays.",
     ["Orthodox", "Christianity", "Islam", "church", "Sunday", "mosque"]),
    ("family", "edu", ["New-en-56", "Ki-pe-24"],
     "English is the most popular foreign language in Ethiopia and is taught in all schools; besides English, students learn Amharic and their regional mother tongue (e.g. Afaan Oromo, Tigrinya).",
     ["English", "Amharic", "Afaan Oromo", "language"]),
    ("family", "general", ["New-en-59", "New-az-39", "New-spme-37"],
     "The most popular emigration destination for Ethiopians is the United States, followed by Middle Eastern countries (Saudi Arabia, UAE, Lebanon) for labour migration, Canada and Europe. Students studying abroad mostly go to the USA, China, India and European countries, often for medicine and engineering.",
     ["USA", "United States", "Saudi Arabia", "emigration", "study abroad"]),
    ("family", "general", ["New-ko-04", "New-ko-05"],
     "Popular toys in Ethiopia: boys play with balls (football) and toy cars; girls play with dolls and skipping ropes.",
     ["football", "toy car", "doll", "toys"]),
    ("family", "general", ["New-ko-03", "New-ko-06"],
     "Ethiopian children grow up with oral folk tales (teret, ተረት) told by grandparents and songs such as \"Abebayehosh\", sung by girls at the New Year.",
     ["teret", "folk tale", "Abebayehosh", "song"]),
    ("family", "hol", ["New-spme-65", "Kik-in-02", "New-spme-76"],
     "Ethiopia has no independence day because it was never colonised. The closest national celebration is Adwa Victory Day (2 March), celebrated with parades and patriotic songs at Menelik II Square in Addis Ababa; Patriots' Victory Day (5 May) is also commemorated.",
     ["independence day", "never colonised", "Adwa Victory Day", "Menelik Square"]),
    ("family", "general", ["New-su-75", "Th-en-43"],
     "Most Ethiopian families do not own a car (typically 0 cars); people rely on minibus taxis, buses and bajaj (three-wheelers). Car owners mostly drive Toyota models (Vitz, Corolla).",
     ["car", "Toyota", "bajaj", "minibus"]),
    ("family", "general", ["Sa-en-31"],
     "Dogs (often kept as guards) and cats are the most common pets in Ethiopia.",
     ["dog", "cat", "pet"]),
    ("family", "culture", ["Sa-en-37", "Th-en-39", "New-as-76", "New-pe-83"],
     "Popular Ethiopian family games are gebeta (a mancala board game), carrom (kerem), checkers, card games and dominoes; at Christmas boys play genna, a hockey-like stick game.",
     ["gebeta", "mancala", "carrom", "cards", "genna"]),
    ("family", "general", ["Ta-pe-10", "Ta-pe-11", "Th-en-41"],
     "In Ethiopian cities men usually marry around age 28-30 and women around 23-25, and couples typically have their first child within a year or two of marriage (around 25); in rural areas people marry much younger.",
     ["marriage age", "men", "women", "first child"]),
    ("family", "general", ["Th-en-37", "Ji-ko-26"],
     "Ethiopian children usually live with their parents until they marry or get a job, often into their mid-twenties; key milestones of independence are finishing university, getting a job and marriage.",
     ["independence", "marriage", "job", "parents"]),
    ("family", "culture", ["Th-en-45", "Al-en-43"],
     "A typical Ethiopian family evening or indoor activity is a coffee ceremony together, eating dinner together and watching TV.",
     ["coffee ceremony", "TV", "dinner", "family"]),
    ("family", "general", ["Nu-in-20"],
     "International Children's Day (1 June) is recognised in Ethiopia.",
     ["Children's Day", "June 1"]),

    # ---------------- education ----------------
    ("education", "edu", ["Al-en-16", "Jo-sp-39", "Gu-ch-31", "Ni-en-15"],
     "In Ethiopia kindergarten (pre-primary) starts at about age 4, and grade 1 of primary school starts at age 7. Under the 2023 Education and Training Policy schooling is pre-primary, primary (grades 1-6), middle (grades 7-8) and secondary (grades 9-12); the older system had 8 years of primary. Middle school therefore starts around age 13.",
     ["kindergarten", "age 4", "age 7", "primary school", "grade 1"]),
    ("education", "edu", ["Gu-ch-32", "Ni-en-06", "Ki-pe-17", "New-spme-27"],
     "Formal education in Ethiopia has 12 grades; primary education (to grade 8) is free and intended to be compulsory from age 7. Many Ethiopians, especially in rural areas, complete only primary school; in cities most finish secondary school.",
     ["compulsory education", "12 grades", "primary", "secondary"]),
    ("education", "edu", ["New-am-41", "Th-en-49", "Ji-ko-42"],
     "Ethiopian students sit regional exams in grades 6 and 8 and the national Grade 12 exam (Ethiopian Secondary School Leaving Certificate Examination / university entrance exam), the most important exam for high school students; earlier there was also a national Grade 10 exam (EGSECE). Mathematics, English and aptitude are taken by all students, with natural- or social-science subjects by stream.",
     ["grade 12 exam", "national exam", "university entrance exam", "grade 10", "grade 8"]),
    ("education", "edu", ["Gu-ch-38", "Ni-en-11", "Ni-en-03", "Ni-en-13"],
     "Undergraduate degrees in Ethiopia usually take 4 years (engineering 5, medicine 6); a Master's degree takes about 2 years. Students enter university at about 18-19 and graduate around 22-23.",
     ["4 years", "undergraduate", "Master's", "2 years", "university"]),
    ("education", "edu", ["Gu-ch-33", "An-ar-09", "Jo-sp-43", "Al-en-19"],
     "In Ethiopia children learn in their mother tongue in early primary school and study English as a subject from grade 1 (around age 7); Amharic is taught as an additional language in non-Amharic regions. High school students usually study 2-3 languages (English, Amharic, and a regional language), with English the main second language and medium of instruction.",
     ["English", "Amharic", "mother tongue", "language", "grade 1"]),
    ("education", "general", ["Nu-in-05", "An-ar-03", "Nu-in-04", "New-en-70", "Jo-sp-36"],
     "The Ethiopian school year starts in September (Meskerem), right after the Ethiopian New Year, and ends in June; it has two semesters, with final exams in June. The long summer break covers the rainy season (kiremt), July and August (about 8-10 weeks).",
     ["September", "Meskerem", "two semesters", "June", "summer break"]),
    ("education", "general", ["Ki-pe-30", "Ni-en-09"],
     "Ethiopian schools are open five days a week (Monday to Friday) and closed on Saturday and Sunday.",
     ["five days", "Saturday", "Sunday", "weekend"]),
    ("education", "general", ["Nu-in-11", "Gu-ch-40", "Jo-sp-31", "Ni-en-02", "An-ar-08"],
     "Ethiopian schools usually start at 8:00 (2:00 in Ethiopian local time). Many government schools run in shifts: the morning shift ends around 12:30 and the afternoon shift runs until about 17:00; full-day schools finish around 15:30-16:00. Students spend roughly 6-7 hours a day at school.",
     ["8:00", "shift", "12:30", "school hours"]),
    ("education", "general", ["Ni-en-12", "New-in-62", "New-in-63"],
     "Addis Ababa University (AAU, founded 1950) is Ethiopia's top university; its Addis Ababa Institute of Technology is the best-known engineering school, and its College of Health Sciences (Black Lion/Tikur Anbessa Hospital) the best-known medical school. Other well-known universities are Jimma University, University of Gondar, Bahir Dar University, Haramaya University and Adama Science and Technology University.",
     ["Addis Ababa University", "AAU", "Jimma University", "University of Gondar", "Bahir Dar University"]),
    ("education", "general", ["Ji-ko-38", "New-ch-72", "New-ch-31"],
     "Medicine is the most competitive and prestigious major in Ethiopia, followed by engineering and computer science; these, together with accounting and economics, are seen as best for employment, and many parents hope their children become doctors or engineers.",
     ["medicine", "engineering", "doctor", "computer science"]),
    ("education", "general", ["Al-en-18", "Ji-ko-35", "Ji-ko-36", "Th-en-51", "Al-en-21"],
     "Private tutoring is the most common form of private education in Ethiopia, usually a tutor coming to the student's home; the most tutored subjects are mathematics, English and physics. Mathematics and English are considered the most important subjects.",
     ["tutor", "tutoring", "mathematics", "English", "physics"]),
    ("education", "general", ["Ji-ko-37", "Ji-ko-41", "New-su-33"],
     "Ethiopian students wear school uniforms (each school has its own colour) with ordinary shoes or sneakers. Teachers dress formally and many wear a white coat (gown) in class.",
     ["uniform", "school uniform", "white coat", "shoes"]),
    ("education", "general", ["An-ar-02", "New-ch-74"],
     "Students at Ethiopian public universities live in campus dormitories and eat in the university cafeteria, which are provided under the cost-sharing system; students at private colleges live with family or in rented rooms.",
     ["dormitory", "cafeteria", "campus", "university"]),
    ("education", "general", ["Ji-ko-31", "Tmp-ar-01", "New-am-34", "Ji-ko-33"],
     "Ethiopian students usually study for exams at home or in libraries (school, university and public libraries), and university students study in the campus library or dorm.",
     ["library", "home", "study"]),
    ("education", "general", ["Ji-ko-34", "Tmp-ar-02"],
     "Most Ethiopian elementary students walk to school; private-school students often use school buses. University students commute by minibus taxi, city bus (Anbessa, Sheger) or the Addis Ababa light rail.",
     ["walk", "on foot", "school bus", "minibus taxi", "bus"]),
    ("education", "general", ["New-ch-70"],
     "First-year (freshman) students at Ethiopian universities take common courses such as Communicative English, Logic and Critical Thinking, Mathematics, Civics and Moral Education, General Psychology, Anthropology, Geography of Ethiopia and the Horn, History of Ethiopia and the Horn, Physical Fitness and Entrepreneurship.",
     ["freshman courses", "Communicative English", "Logic and Critical Thinking", "Civics"]),
    ("education", "general", ["New-en-69"],
     "Writers commonly studied in Ethiopian literature classes include Haddis Alemayehu (Fikir Eske Mekabir), Bealu Girma (Oromay), Tsegaye Gabre-Medhin, Kebede Michael and Abe Gubegna.",
     ["Haddis Alemayehu", "Fikir Eske Mekabir", "Bealu Girma", "Tsegaye Gabre-Medhin"]),
    ("education", "general", ["Tmp-ar-04", "Ji-ko-40", "New-pe-66", "Th-en-53", "New-ch-73"],
     "After school Ethiopian children do homework, play football and help with household chores. At break time students chat, play and eat snacks. Popular school activities are clubs (mini-media, drama, environment, Red Cross), sports and the annual school day/parents' day; at university religious fellowships and clubs are popular.",
     ["homework", "football", "chores", "clubs", "mini-media"]),
    ("education", "general", ["Gu-ch-41", "Ji-ko-39", "New-su-34"],
     "Most Ethiopian elementary students do not learn a musical instrument at school; school music activities are mostly singing and school bands, and traditional instruments are the krar, masenqo, washint and kebero.",
     ["no instrument", "singing", "krar", "masenqo"]),
    ("education", "general", ["Al-en-17", "Jo-sp-32", "An-ar-34", "Na-ko-17", "Kik-in-45"],
     "Football (soccer) is the most popular sport at Ethiopian schools, played at break, after school and in PE; schools typically have a football field and volleyball and basketball courts. Athletics (running) and volleyball are also common.",
     ["football", "soccer", "volleyball", "athletics", "school sport"]),
    ("education", "general", ["New-ch-71", "New-ch-75"],
     "Ethiopian public high school classes are large, often 50-60 students; a class period lasts about 40-45 minutes.",
     ["class size", "50", "40 minutes"]),
    ("education", "general", ["New-su-42"],
     "Ethiopian public schools are secular and do not teach religion; civics and ethical education is taught instead. Religious schools (Orthodox church schools and Islamic madrasas) exist separately.",
     ["no religion", "secular", "civics"]),
    ("education", "general", ["Th-en-48"],
     "Ethiopian schools grade out of 100%, and universities use letter grades where A+ / A (4.0 GPA) is the highest grade.",
     ["A", "A+", "100", "grade"]),
    ("education", "general", ["New-en-72"],
     "Ethiopian students commonly use YouTube, Telegram study channels and Google to study online.",
     ["YouTube", "Telegram", "Google"]),
    ("education", "general", ["New-pe-74", "New-ch-66"],
     "Public schools in Ethiopia are free, and public universities use cost-sharing: tuition, food and dormitory costs are paid back after graduation through tax deductions.",
     ["free", "cost-sharing", "tuition"]),

    # ---------------- sports ----------------
    ("sports", "sport", ["Gu-ch-08", "Gu-ch-06", "Jod-ch-38", "New-as-29", "Gu-ch-15", "Kik-in-34", "Th-en-03"],
     "Football (soccer, እግር ኳስ) is the most popular sport in Ethiopia to play and watch, especially among men and children; the English Premier League is followed passionately (Arsenal, Manchester United and Chelsea have huge Ethiopian fan bases), and the Ethiopian Premier League is the main domestic league.",
     ["football", "soccer", "English Premier League", "Arsenal", "Manchester United"]),
    ("sports", "sport", ["Jo-sp-01", "Jo-sp-02", "Th-en-12", "Gu-ch-11", "New-gr-24", "New-ch-18", "Ta-pe-17", "New-ch-30"],
     "Athletics, especially long-distance running (ሩጫ), is Ethiopia's second most popular sport and the one in which it is most successful internationally; most of Ethiopia's Olympic gold medals were won in the 10,000 m, 5,000 m and marathon, which are the most watched events.",
     ["athletics", "running", "long-distance", "10000m", "marathon", "Olympics"]),
    ("sports", "sport", ["Th-en-11", "New-ch-30", "New-am-27"],
     "The most famous Ethiopian athletes are Haile Gebrselassie (ኃይሌ ገብረሥላሴ), Kenenisa Bekele and Abebe Bikila (the first African Olympic champion, who won the 1960 marathon barefoot). The most famous female athletes are Tirunesh Dibaba, Derartu Tulu (first African woman Olympic champion), Meseret Defar, Almaz Ayana and Letesenbet Gidey.",
     ["Haile Gebrselassie", "Kenenisa Bekele", "Abebe Bikila", "Tirunesh Dibaba", "Derartu Tulu"]),
    ("sports", "derby", ["An-ar-36", "Sa-en-16", "Kik-in-37", "Ta-pe-25", "Kik-in-38"],
     "Saint George (Kidus Giorgis, ቅዱስ ጊዮርጊስ) is Ethiopia's most popular and most successful football club. Its fierce rivalry with Ethiopian Coffee (Ethiopia Bunna) is the Sheger Derby in Addis Ababa; other big clubs are Fasil Kenema, Sidama Coffee, Mekelle 70 Enderta and Bahir Dar Kenema.",
     ["Saint George", "Ethiopian Coffee", "Sheger Derby", "Fasil Kenema"]),
    ("sports", "sport", ["Na-ko-20", "New-gr-29", "Th-en-09"],
     "Ethiopians most passionately support their athletes at the Olympic Games and World Athletics Championships; football fans follow the Africa Cup of Nations, which Ethiopia won in 1962, and the World Cup.",
     ["Olympics", "World Athletics Championships", "Africa Cup of Nations", "1962"]),
    ("sports", "general", ["New-su-28", "Na-ko-22"],
     "Ethiopia's national football team, nicknamed the Walia Ibex (Walyas), plays in the national colours green, yellow and red.",
     ["Walia", "green", "yellow", "red", "national team"]),
    ("sports", "general", ["Na-ko-16", "Kik-in-36"],
     "Famous Ethiopian footballers include Mengistu Worku (1962 AFCON hero), Saladin Said and Getaneh Kebede; coach Sewnet Bishaw led Ethiopia back to the Africa Cup of Nations in 2013.",
     ["Mengistu Worku", "Saladin Said", "Getaneh Kebede", "Sewnet Bishaw"]),
    ("sports", "general", ["An-ar-43"],
     "Ethiopians usually watch football in cafés, bars and small paid TV viewing rooms (often called \"football houses\"), or at home.",
     ["cafe", "bar", "viewing room", "home"]),
    ("sports", "general", ["Gu-ch-09", "Jod-ch-37", "New-as-30", "Na-ko-18", "Ta-pe-22"],
     "Ethiopian women most often do running/athletics, volleyball and aerobics or gym exercise; women commonly watch athletics and football. Girls in PE most often play volleyball or run.",
     ["running", "volleyball", "aerobics", "women", "athletics"]),
    ("sports", "general", ["Gu-ch-05", "Na-ko-26", "New-su-21", "Ta-pe-23"],
     "Older and middle-aged Ethiopians commonly exercise by walking and jogging (e.g. early morning runs at Meskel Square, Jan Meda or Entoto); men also go to the gym or play football.",
     ["walking", "jogging", "gym", "Meskel Square", "Entoto"]),
    ("sports", "sport", ["New-pe-16", "New-ha-19"],
     "Ethiopian traditional sports include genna (a hockey-like game played at Christmas), gugs (a horseback game with lances, so the horse is the main sporting animal) and stick fighting (donga) among the Surma.",
     ["genna", "gugs", "horse", "donga", "stick fighting"]),
    ("sports", "general", ["New-ch-16"],
     "The most famous sports film about Ethiopia is \"Endurance\" (1999), about Haile Gebrselassie; \"Atletu\" (2009) tells the story of Abebe Bikila.",
     ["Endurance", "Atletu", "film"]),
    ("sports", "general", ["New-en-19", "Sa-en-22"],
     "The most well-known stadium in Ethiopia is Addis Ababa Stadium; Bahir Dar Stadium and the new Adey Abeba Stadium are also major venues.",
     ["Addis Ababa Stadium", "Bahir Dar Stadium", "stadium"]),
    ("sports", "general", ["New-as-20", "New-gr-21", "Kik-in-31"],
     "Popular indoor sports in Ethiopia are table tennis, basketball, volleyball and billiards (pool), which is very popular among young men; taekwondo and karate are the most practised martial arts.",
     ["table tennis", "basketball", "billiards", "pool", "taekwondo"]),
    ("sports", "general", ["Th-en-09", "Ta-pe-30"],
     "The Great Ethiopian Run, a 10 km road race in Addis Ababa every November founded by Haile Gebrselassie, is the biggest mass running event in Africa.",
     ["Great Ethiopian Run", "10 km", "Addis Ababa"]),
    ("sports", "general", ["Ta-pe-21", "New-su-24"],
     "Ethiopian children usually play football in streets, open fields and school grounds, often with home-made balls; parents and children play football together.",
     ["street", "open field", "football"]),
    ("sports", "general", ["Kik-in-44", "Ta-pe-29"],
     "Athletics receives the most government support in Ethiopia; football and athletics (prize money from international races) are the best-paying professional sports.",
     ["athletics", "government support", "football"]),

    # ---------------- holidays / celebrations / leisure ----------------
    ("holidays_celebrations_leisure", "hol", ["Jod-ch-16", "New-am-77", "Jod-ch-30", "New-ch-83"],
     "The biggest festivals in Ethiopia are Meskel (መስቀል, Finding of the True Cross, 27 September), celebrated with a huge Demera bonfire and yellow Meskel daisies (Adey Abeba), and Timket (ጥምቀት, Epiphany, 19 January), celebrated with processions of the tabot and re-enactment of Christ's baptism; both are UNESCO-listed. Gondar is famous for Timket and Addis Ababa's Meskel Square for Meskel.",
     ["Meskel", "Timket", "Demera", "Adey Abeba", "bonfire", "Epiphany"]),
    ("holidays_celebrations_leisure", "hol", ["Al-en-34", "Ne-ar-11", "Ca-sp-29", "Ta-pe-37", "Kik-in-07"],
     "The Ethiopian New Year, Enkutatash (እንቁጣጣሽ), is on 11 September. People wear traditional white clothes, girls go door to door singing \"Abebayehosh\" and receive money or bread, children give drawings of flowers, the yellow Adey Abeba flower is the symbol, and families slaughter a chicken or sheep for doro wat and go to church.",
     ["Enkutatash", "New Year", "September 11", "Abebayehosh", "Adey Abeba"]),
    ("holidays_celebrations_leisure", "hol", ["Al-en-35", "Al-en-37", "Ni-en-31", "New-ch-80"],
     "Ethiopian Christmas, Genna (ገና), is on 7 January after a 43-day fast. People attend all-night church services dressed in white netela shawls, boys play the genna stick game, and families eat doro wat with injera. Many pilgrims go to Lalibela for Genna.",
     ["Genna", "Christmas", "January 7", "doro wat", "church", "Lalibela"]),
    ("holidays_celebrations_leisure", "hol", ["New-gr-76", "Th-en-38"],
     "Fasika (ፋሲካ, Ethiopian Easter) ends the 55-day Lenten fast (Abiy Tsom). After a midnight church service families break the fast with doro wat, raw meat and other meat dishes, often slaughtering a sheep, goat or ox.",
     ["Fasika", "Easter", "doro wat", "fast", "sheep"]),
    ("holidays_celebrations_leisure", "hol", ["Ne-ar-05", "Kik-in-01"],
     "Ethiopian national holidays include Adwa Victory Day (2 March), Patriots' Victory Day (5 May), Downfall of the Derg (28 May) and Enkutatash (11 September). Timket is celebrated over about three days (Ketera eve, Timket, and St. Michael's day).",
     ["Adwa Victory Day", "national holiday", "Timket", "three days"]),
    ("holidays_celebrations_leisure", "hol", ["Ne-ar-14", "New-su-77"],
     "At Eid al-Fitr Ethiopian Muslims gather for mass prayer (in Addis Ababa at the stadium and Meskel Square), then celebrate at home with family; children get new clothes and money.",
     ["Eid", "prayer", "new clothes", "money", "Muslim"]),
    ("holidays_celebrations_leisure", "hol", ["Kik-in-08"],
     "Before Ramadan Ethiopian Muslims clean their homes, buy food supplies and prepare spices and dates for iftar.",
     ["Ramadan", "preparation", "dates"]),
    ("holidays_celebrations_leisure", "wedding", ["New-am-81"],
     "The busiest wedding season in Ethiopia runs from Genna (January, the month of Tir) through Timket to before the Lenten fast (March); thousands of weddings take place in January.",
     ["wedding season", "January", "Tir", "Timket"]),
    ("holidays_celebrations_leisure", "general", ["Kik-in-06", "Na-ko-38", "Na-ko-39"],
     "Before an Ethiopian wedding, elders (shimagile) are sent to ask the bride's family for marriage, followed by an engagement; the groom gives the bride gifts (telosh) such as clothes and jewellery. Wedding guests usually give money or household items.",
     ["shimagile", "engagement", "telosh", "money", "gift"]),
    ("holidays_celebrations_leisure", "general", ["New-su-81", "New-su-82", "New-ch-84", "New-ha-66"],
     "At Ethiopian weddings brides wear a white wedding dress or a white habesha kemis, and grooms a suit or traditional habesha clothes with a cape; guests wear traditional white habesha clothing or formal wear. Weddings are held in hotels, halls or a large tent at home.",
     ["white dress", "habesha kemis", "suit", "hotel", "tent"]),
    ("holidays_celebrations_leisure", "general", ["New-su-83", "New-gr-89", "New-az-73"],
     "Ethiopian wedding feasts feature injera with doro wat, raw meat, kitfo and tibs, with tej, tella, beer and soft drinks; weddings are large, often with several hundred guests.",
     ["wedding food", "doro wat", "raw meat", "tej", "hundreds of guests"]),
    ("holidays_celebrations_leisure", "general", ["Kik-in-04", "Na-ko-40", "Na-ko-41", "Na-ko-42", "New-gr-88", "New-ch-85", "New-ko-07"],
     "When someone dies in Ethiopia a mourning tent (dass) is put up in front of the house, and mourners come for about three days (lekso) and on the 40th day memorial. Mourners wear black and bring bread, injera, food, coffee or money; community burial associations (edir) help pay for the funeral. Coffee and tea are served to mourners.",
     ["mourning tent", "dass", "lekso", "black", "edir", "three days"]),
    ("holidays_celebrations_leisure", "culture", ["New-am-83", "New-gr-82", "New-su-88"],
     "The most popular traditional Ethiopian instruments are the krar (lyre), masenqo (one-string fiddle), washint (flute), kebero (drum) and begena. Older people enjoy traditional and Orthodox religious music and classic singers like Tilahun Gessesse and Mahmoud Ahmed; young people listen to Ethiopian pop, hip-hop and artists such as Teddy Afro.",
     ["krar", "masenqo", "washint", "kebero", "Teddy Afro"]),
    ("holidays_celebrations_leisure", "culture", ["New-as-80", "New-as-89", "Kik-in-15"],
     "At festivals Ethiopians wear traditional white cotton clothing: women wear the habesha kemis with colourful embroidered borders (tibeb) and a netela shawl, men wear white traditional suits; accessories include cross necklaces, gold or silver jewellery and headbands.",
     ["habesha kemis", "netela", "white", "cross necklace", "jewellery"]),
    ("holidays_celebrations_leisure", "general", ["Kik-in-10", "New-en-87", "Kik-in-11"],
     "The most famous Ethiopian landmarks and attractions are the rock-hewn churches of Lalibela, the obelisks of Axum, Fasil Ghebbi castle in Gondar, the Simien Mountains, Blue Nile Falls and the Danakil Depression; Lalibela and Axum (St Mary of Zion) are the main religious sites.",
     ["Lalibela", "Axum", "Gondar", "Simien Mountains", "Blue Nile Falls"]),
    ("holidays_celebrations_leisure", "general", ["New-pe-86", "New-su-86", "New-en-90", "New-en-76", "New-in-80"],
     "Notable Addis Ababa buildings: the Commercial Bank of Ethiopia headquarters is the tallest tower; the Grand (Menelik) Palace and Parliament are the best-known government buildings, and Unity Park opened at the palace grounds. Sheraton Addis, Hilton Addis, Skylight and Haile Resorts are the most famous hotels; Bole International Airport is the main airport.",
     ["Commercial Bank of Ethiopia", "Menelik Palace", "Unity Park", "Sheraton Addis", "Bole"]),
    ("holidays_celebrations_leisure", "general", ["New-in-78"],
     "Cash is the most common payment method in Ethiopia, with mobile money (telebirr, CBE Birr) and bank transfers growing quickly.",
     ["cash", "telebirr", "mobile money"]),
    ("holidays_celebrations_leisure", "general", ["Jod-ch-41", "Jod-ch-42", "New-ch-78", "New-ch-79", "New-pe-76"],
     "Common leisure for young Ethiopian women is meeting friends at cafés, shopping and social media; young men watch football, play pool (billiards) and meet in cafés. Retired men chat over coffee, play cards or checkers and go to church; retired women hold coffee ceremonies, visit neighbours and attend church associations. In parks people walk, picnic and take photos.",
     ["cafe", "pool", "billiards", "football", "coffee ceremony", "church"]),
    ("holidays_celebrations_leisure", "general", ["Jod-ch-28", "New-pe-85"],
     "Ethiopians usually travel between cities by long-distance bus (e.g. Selam Bus, Sky Bus); popular foreign destinations are Dubai and other Middle East countries.",
     ["bus", "Selam Bus", "Dubai"]),
    ("holidays_celebrations_leisure", "general", ["Al-en-38", "Ni-en-37"],
     "Valentine's Day (14 February) is celebrated in Ethiopian cities with red roses, chocolates and red clothing.",
     ["Valentine's Day", "roses", "red"]),
    ("holidays_celebrations_leisure", "general", ["New-pe-78", "New-en-79"],
     "The Addis International Film Festival is Ethiopia's best-known film festival; Addis Ababa is the centre of theatre (National Theatre, Hager Fikir Theatre).",
     ["Addis International Film Festival", "National Theatre", "Hager Fikir"]),

    # ---------------- work life ----------------
    ("work_life", "labour", ["Ni-en-17", "Jod-ch-60", "Ji-ko-08", "Ni-en-19"],
     "Ethiopian labour law sets normal working hours at no more than 8 hours a day and 48 hours a week; full-time workers usually work 5 to 5.5 days a week (many private employers work Saturday morning).",
     ["8 hours", "48 hours", "working week", "five days"]),
    ("work_life", "general", ["Ne-ar-17", "Ne-ar-18", "Ki-pe-51", "Ki-pe-53", "Jo-sp-21", "Ji-ko-15", "Jod-ch-46"],
     "Ethiopian government offices work from 8:30 to 12:30 and 13:30 to 17:30 (2:30-11:30 in Ethiopian local time), Monday to Friday; the lunch break is about one hour, starting around 12:30.",
     ["8:30", "17:30", "12:30", "lunch break", "one hour"]),
    ("work_life", "labour", ["Jo-sp-18", "Jod-ch-54", "New-ch-44", "Ni-en-21"],
     "Under Ethiopian labour law workers get 16 working days of annual leave in the first year (plus one day for every two additional years), 3 working days of marriage leave and 3 days of mourning leave; probation lasts at most 60 working days, and employing anyone under 15 is prohibited.",
     ["16 days", "annual leave", "marriage leave", "3 days", "60 days", "15 years"]),
    ("work_life", "general", ["Jod-ch-56", "Jod-ch-57", "Ni-en-20"],
     "The retirement age in Ethiopia is 60 for both men and women. Most people start working after finishing school or university, around 18-22.",
     ["retirement age", "60", "start working"]),
    ("work_life", "general", ["Ne-ar-16"],
     "The weekend in Ethiopia is Saturday and Sunday.",
     ["weekend", "Saturday", "Sunday"]),
    ("work_life", "general", ["Jod-ch-51", "Jod-ch-50"],
     "Most workers in Addis Ababa commute by blue-and-white minibus taxis and city buses (Anbessa, Sheger), the light rail, or on foot; commutes often take 30-60 minutes.",
     ["minibus taxi", "bus", "light rail", "walking"]),
    ("work_life", "general", ["Ne-ar-20", "Jod-ch-58", "Jod-ch-61", "Jod-ch-62", "Ne-ar-25", "New-gr-58"],
     "Government jobs and bank jobs are considered the most secure in Ethiopia. Doctors are the most respected profession; women often prefer nursing, teaching and banking, and men engineering, medicine and business. Aviation (Ethiopian Airlines), banking, telecoms and NGOs pay best, while teachers and nurses are considered underpaid.",
     ["government job", "bank", "doctor", "teacher", "Ethiopian Airlines"]),
    ("work_life", "economy", ["Ne-ar-26", "Ji-ko-07", "Th-en-27"],
     "Ethiopian Airlines, Africa's largest airline, is Ethiopia's most famous state-owned company; Ethio Telecom and the Commercial Bank of Ethiopia are other major public enterprises. Agriculture is the most important industry, employing about 70% of the labour force, with coffee the top export.",
     ["Ethiopian Airlines", "Ethio Telecom", "Commercial Bank of Ethiopia", "agriculture", "coffee"]),
    ("work_life", "general", ["Ji-ko-07", "New-en-41"],
     "Well-known Ethiopian private companies include MIDROC Ethiopia (owned by Mohammed Al Amoudi), Dashen Bank, Awash Bank and Safaricom Ethiopia; famous entrepreneurs include Mohammed Al Amoudi, Haile Gebrselassie (hotels and businesses) and Bethlehem Tilahun Alemu (soleRebels).",
     ["MIDROC", "Mohammed Al Amoudi", "Haile Gebrselassie", "Bethlehem Tilahun Alemu"]),
    ("work_life", "general", ["Ne-ar-24", "Ji-ko-03", "Nu-in-40", "Th-en-24"],
     "Addis Ababa is Ethiopia's commercial and financial hub (home to Merkato, one of Africa's largest open-air markets), the main destination for job seekers, and the hub for tech workers and start-ups.",
     ["Addis Ababa", "Merkato", "commercial hub"]),
    ("work_life", "economy", ["New-ch-38", "Th-en-19"],
     "Ethiopia's trade runs through the Addis Ababa-Djibouti corridor (railway and road) via Dire Dawa and the Modjo dry port. Manufacturing is concentrated in industrial parks at Hawassa, Bole Lemi (Addis Ababa), Dukem (Eastern Industrial Zone), Adama and Kombolcha.",
     ["Djibouti", "Dire Dawa", "Modjo", "Hawassa Industrial Park", "Bole Lemi"]),
    ("work_life", "general", ["New-am-53", "Jo-sp-19", "New-am-54"],
     "Ethiopia's famous coffee regions are Sidama, Yirgacheffe (Gedeo), Jimma, Kaffa and Harar. Oromia and Amhara are the main agricultural regions, and the lowlands of Borana, Somali and Afar are known for livestock herding.",
     ["Sidama", "Yirgacheffe", "Jimma", "Harar", "Oromia", "Borana"]),
    ("work_life", "general", ["New-in-33", "New-in-34"],
     "Gold mining in Ethiopia is centred in Oromia (Shakiso, Lega Dembi) and Benishangul-Gumuz; oil and gas are found in the Ogaden basin of the Somali Region (Calub and Hilala gas fields).",
     ["gold", "Shakiso", "Benishangul-Gumuz", "Ogaden", "Somali Region"]),
    ("work_life", "general", ["Th-en-22"],
     "The most catastrophic period for Ethiopia's economy was the 1983-1985 famine under the Derg regime.",
     ["famine", "1984", "Derg"]),
    ("work_life", "general", ["New-am-59", "New-su-50", "New-su-51", "New-am-60", "New-su-57", "New-su-58"],
     "In Ethiopia's desert lowlands (Afar, Somali) people are mainly pastoralists, and Afar also mines salt; in the highlands and mountains people farm (teff, barley, wheat) and raise livestock. Ethiopia is landlocked, so there is no coastal fishing. Cattle are the most common livestock (Ethiopia has Africa's largest livestock population), with sheep, goats and chickens; oxen plough the fields and donkeys (and camels in the lowlands) carry goods.",
     ["pastoralism", "farming", "cattle", "oxen", "donkey", "camel"]),
    ("work_life", "general", ["New-su-59"],
     "Ethiopian farmers protect themselves from the sun with straw hats and cotton gabi or netela shawls.",
     ["straw hat", "gabi", "netela"]),
    ("work_life", "general", ["Th-en-21", "Ji-ko-02", "New-ko-09"],
     "Valued perks for Ethiopian employees are transport service (staff buses), health insurance and lunch allowance. Company get-togethers usually involve a meal of injera, raw meat and tibs with beer, and team-building trips to resorts in Bishoftu or Adama.",
     ["staff bus", "transport", "health insurance", "Bishoftu"]),
    ("work_life", "general", ["New-ko-10", "New-ko-08", "New-ch-45", "New-ch-39"],
     "Common side jobs in Ethiopia are tutoring, ride-hailing driving (Ride, Feres), brokerage (delala) and small trade; university students work part-time as tutors or in cafés. Young entrepreneurs start cafés, trading, tech start-ups and online shops, often selling through Telegram and Facebook.",
     ["tutoring", "Ride", "broker", "Telegram", "small business"]),
    ("work_life", "general", ["New-az-49"],
     "In a typical Ethiopian family one or two people (often the father, or both parents in cities) work for income.",
     ["one", "two", "father", "breadwinner"]),
    ("work_life", "general", ["New-pe-45"],
     "Ethiopia's working hours do not change officially during Ramadan, although Muslim workers may shorten breaks to leave earlier for iftar.",
     ["Ramadan", "working hours", "no change"]),
]
